
  - apt: name=xorg
  - apt: name=xmonad
  - apt: name=xmobar
  - apt: name=xtrlock
  - apt: name=dmenu
  - apt: name=iceweasel
  - apt: name=evince
  - apt: name=ircii
  - apt: name=mplayer
  - apt: name=cifs-utils # to mount shares

  # - apt: name=virtualbox
  # - apt: name=vagrant

