
  # see, https://grails.org/download.html

  - file:
      path: "{{grails_deploy_path}}"
      state: directory

  - apt: name=unzip



  # 2.4.4
  - get_url: >
      url='https://github.com/grails/grails-core/releases/download/v2.4.4/grails-2.4.4.zip'
      dest={{grails_deploy_path}}/grails-2.4.4.zip

  - unarchive: >
      copy=no
      src={{grails_deploy_path}}/grails-2.4.4.zip
      dest={{grails_deploy_path}}
      creates={{grails_deploy_path}}/grails-2.4.4/LICENSE

