

  # expect jdk-1.7 and grails-1.3.7 are already installed

  # checkout aatams source
  - shell: creates="{{aatams_src_path}}" chdir="{{aatams_src_path}}/.." {{item}}
    become: yes
    become_user: "{{user}}"
    with_items:
      - git clone https://github.com/aodn/aatams/


  # set path dependencies
  - copy:
      dest: "/home/{{user}}/imports.sh"
      content: |
        # deployed by ansible!
        export JAVA_HOME=$HOME/jdk1.7.0_80/
        export PATH="$JAVA_HOME/bin:$PATH"

        export GRAILS_HOME=$HOME/grails-1.3.7/
        export PATH="$PATH:$GRAILS_HOME/bin"

  # compile
  - shell:  chdir="{{aatams_src_path}}" {{item}}
    become: yes
    become_user: "{{user}}"
    with_items:
      - . ../imports.sh && grails prod war 2>&1 | tee build-log.txt



