
# debian version of node is out of date...
# we don't set any paths, which should be in scripts

  - get_url: >
      url='https://nodejs.org/dist/v6.11.0/node-v6.11.0-linux-x64.tar.xz'
      dest="{{node_deploy_path}}/node-v6.11.0-linux-x64.tar.xz"
      mode=644

  - unarchive:
      src: "{{node_deploy_path}}/node-v6.11.0-linux-x64.tar.xz"
      dest: "{{node_deploy_path}}"
      remote_src: True

# this should be in /scripts/...
#
#  # use .profile or .bashrc?
#  #  Note that rustup writes over .profile
#  - copy:
#      dest: /home/{{node.user}}/.bash_aliases1
#      mode: 0755
#      content: |
#        export PATH="/home/{{node.user}}/node-v6.11.0-linux-x64/bin:$PATH"
#




#################

# OLD on Debian
#  - apt: name=nodejs                        # node/nodejs v4.2.4
#  - npm: name=npm state=latest global=true  # 2.14.12 -> 3.5.3

      #
  # https://nodejs.org/en/download/package-manager/


#################
#
#  - shell: |
#      curl -sL https://deb.nodesource.com/setup_4.x | bash -
#      creates=/etc/apt/sources.list.d/nodesource.list



#################

#  - apt: name=npm
  # Don't need when using deb.nodesource.com ...
  # debian legacy workaround
  # - file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

  #  - apt: name=npm
  # upgrade to latest npm 3.5.2
  # - npm: name=npm global=true

  # upgrade/ensure using nodejs 4.2.4. 4.2.0 is the LTS
  # - npm: name=nodejs global=true


# RUN npm install -g gulp

## dont really need this.
# express
# RUN npm install express body-parser

# websockets
# RUN apt-get -y install python g++
# RUN npm install ws


