
# moved to ethernet-bridge
#  - name: restart-br0
#    command: sh -c "/sbin/ifdown br0 && sleep 1 && /sbin/ifup br0"

  - name: restart-dhcp
    service: name=isc-dhcp-server enabled=yes state=restarted

  - name: restart-bind
    service: name=bind9 enabled=yes state=restarted

#  - name: reconfigure-iptables
#    command: "{{item}}"
#    with_items:
#      - sh /etc/iptables-rules
#      - dpkg-reconfigure --frontend noninteractive iptables-persistent
#


  - name: reconfigure-iptables
    command: "{{item}}"
    with_items:
      - sh -c 'm4 /etc/iptables-rules.m4 > /etc/iptables-rules'
      - sh /etc/iptables-rules
      - dpkg-reconfigure --frontend noninteractive iptables-persistent



  - name: restart-rsyslog
    service: name=rsyslog state=restarted


