

  # have to chmod 755 on /home/bitcoin/data
  # does it make sense to use the same user for both services - since they're both trusted the same.

  - copy:
      dest: "{{path}}/lightningd.sh"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0700
      content: |
        #!/bin/bash
        # deployed by ansible!

        PATH="./lightning/lightningd/:$PATH"
        PATH="/nix/var/nix/profiles/default/bin/:$PATH"

        # ndata is bitcoin data dir
        # lightningd --lightning-dir=data --bitcoin-datadir /home/bitcoin/data --network=testnet | json_pp

        # no longer need the bitcoin.conf in the bitcoin datadir... nice.
        lightningd  \
          --bitcoin-rpcuser test \
          --bitcoin-rpcpassword test \
          --bitcoin-rpcconnect 127.00.1 \
          --lightning-dir=data  \
          --network=testnet \
          | json_pp

    tags: config

  - copy:
      dest: "{{path}}/cli.sh"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0700
      content: |
        #!/bin/bash
        # deployed by ansible!

        PATH="./lightning/cli/:$PATH"

        # data is lightning data dir
        lightning-cli --lightning-dir ./data "$@"

    tags: config


  # access bitcoin-cli
  # useful to do from the same account
  - copy:
      dest: "{{path}}/clib.sh"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0700
      content: |
        #!/bin/bash
        # deployed by ansible!

        export PATH="/nix/var/nix/profiles/default/bin/:$PATH"

        # we don't need the datadir
        bitcoin-cli  \
          --rpcuser=test  \
          --rpcpassword=test \
          -testnet \
          $@ | less

    tags: config

    ##################################

    # faucet, https://testnet.manu.backend.hamburg/faucet
    # ln explorer, https://explorer.acinq.co/

    # ./cli.sh help
    # ./cli.sh getinfo
    # ./cli.sh listfunds

    # need address to open a channel
    # ./cli.sh newaddr
    # then send btc from faucet direct

    # check tx with btc
    # ./cli.sh getrawtransaction xxx 1 | grep conF

    # ./cli.sh connect $ch 104.131.26.124 9735

    # should show we are connected. ie. state=gossiping
    # ./cli.sh listnodes
    # ./cli.sh listpeers
    # and should show lots of channels
    # ./cli.sh listchannels

    # fundchannel amount is amount (not fee), in satoshis. ie 1000000 is 0.01btc is locked,

    # ./cli.sh fundchannel $ch 1000000
    # "state" : "CHANNELD_AWAITING_LOCKIN"

    # took 3 confirmations before got state change to CHANNELD_NORMAL

    # can see/and decode tx, and confirmations, using bitcoin cli,
    # ./cli.sh getrawtransaction $tx  1

    # it returns a tx.

    # note. just put in desc, otherwise it's interpreted as the locktime
    # ./cli.sh  invoice 163 'gem3' 'desc' 86400

    # ./cli.sh pay $invoice
    # ./cli.sh listpayments

    # getroute does show a route,
    # ./cli.sh  getroute $n 1 0

    # when reset - must delete THE hsm file, otherwise network/channel state will be preserved
    # based on node identifers.

    # we're not allowed to disconnect, from a peer, because then how would we settle if needed.

