
OBSOLETE

# this is way too complicated...
# and apt loses control over sub-versioning

- shell: creates=oracle-jdk-installed {{item}}
  with_items:
    - echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
    - echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 
    - apt-get update
    - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections 
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
    - DEBIAN_FRONTEND=noninteractive  apt-get install -y --force-yes oracle-java7-installer oracle-java7-set-default
    - rm -rf /var/cache/oracle-jdk7-installer
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*
    - touch oracle-jdk-installed 

    - lineinfile: dest=/home/meteo/paths backup=true state=present insertafter=EOF line='export PATH=$PATH:$HOME/.chefdk/gem/ruby/2.1.0/bin'
