
# Option '--rpccorsdomain' is deprecated. Please use '--jsonrpc-cors' instead.
# Option '--no-ui' has been removed and is no longer supported.
# Option '--no-dapps' has been removed and is no longer supported.

# these should be set elsewhere...
# PATH="$HOME/node-v6.11.0-linux-x64/bin:$PATH"
# PATH="$HOME/solidity/build/solc:$PATH"
# PATH="$HOME/solidity/build/lllc:$PATH"

# should *not* install web3 or other dependencies under same user/group
# can be on entirely different node
# see web3 play
# - devel/node
# - crypto/web3


- copy:
    dest: /home/parity/vars.inc
    content: |
      # deployed by ansible!

      PATH="{{build_dir}}/target/release:$PATH"

      export PATH
  tags: config


- copy:
    dest: /home/parity/start-parity-sync.sh
    owner: parity
    group: parity
    mode: 0700
    content: |
      #!/bin/bash
      # deployed by ansible!

      . ./vars.inc

      # with --no-discovery option - may help on initial sync to avoid
      # getting poisoned blocks. but otherwise will prevent finding new peers
      parity \
        -d data \
        --rpccorsdomain "null" \
        --no-ui --no-ws --no-dapps \
        --allow-ips=public \

  tags: config


- copy:
    dest: /home/parity/start-parity.sh
    owner: parity
    group: parity
    mode: 0700
    content: |
      #!/bin/bash
      # deployed by ansible!

      . ./vars.inc

      # pruning history normally 24
      # --pruning-history 16
      # prevent parity connecting to itself over 127.0.0.1
      # --allow-ips=public
      # don't scan for new peers
      # --no-discovery \
      # pruning fast is default
      # --pruning fast \
      # --min-peers 8 --max-peers 12 \
      # --nat extip:n.n.n.n \
      # --no-warp
      # --no-discovery \

      trickle -s -u 50 -d 100 \
      parity \
        -d data \
        --rpccorsdomain "null" \
        --no-ui --no-ws --no-dapps \
        --allow-ips=public \


  tags: config

# may need port forward for port 30303

# useful - and can avoid installing npm/node
- copy:
    dest: /home/parity/blocknumber.sh
    owner: parity
    group: parity
    mode: 0700
    content: |
      #!/bin/bash
      # deployed by ansible!

      result=$(
      curl -s -X POST \
        -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[ ],"id":1}' \
        http://127.0.0.1:8545
      )

      echo $result

      value=$( echo "$result" | json_pp | grep result | cut -d: -f 2 | sed 's/[\,"]//g' )

      printf "%d\n" $value

  tags: config


