

  - apt: name=cups

  - service: name=cups state=started

  # IMPORTANT no longer idempotent. to allow change configuration.
  # run once only.

  # make idempotent
  #- shell: lpstat -p | grep -q {{pname}}
  #  register: have_printer
  #  ignore_errors: yes
  #  changed_when: "have_printer.rc != 0"

  - copy: src={{ppd}} dest=/tmp

  - shell: |
      # install
      lpadmin \
        -p '{{pname}}' \
        -v '{{url}}' \
        -P '/tmp/{{ppd}}' \
        -E
      # set default
      lpadmin -d {{pname}}

  #  when: "have_printer.rc != 0"


