

  - apt: name=cups

  - service: name=cups state=started

  - shell: lpstat -p | grep -q {{pname}}
    register: have_printer
    ignore_errors: yes
    changed_when: "have_printer.rc != 0"

  - copy: src={{ppd}} dest=/tmp

  - shell: |
      # install
      lpadmin \
        -p '{{pname}}' \
        -v '{{url}}' \
        -P '/tmp/{{ppd}}' \
        -E
      # set default
      lpadmin -d {{pname}}
    when: "have_printer.rc != 0"


