
# test apache2. mar 2021.
# https://linuxize.com/post/secure-apache-with-let-s-encrypt-on-debian-10/
# test, https://www.ssllabs.com/ssltest/analyze.html?d=julian1.io&hideResults=on&latest

- apt: name=apache2


- apache2_module: name={{item}} state=present
  with_items:
    - ssl
    - headers
    - http2


- command: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  args:
    creates:  /etc/ssl/certs/dhparam.pem


- command: "{{item}}"
  args:
    creates:  /var/lib/letsencrypt/done
  with_items:
    - mkdir -p /var/lib/letsencrypt/.well-known
    - chgrp www-data /var/lib/letsencrypt
    - chmod g+s /var/lib/letsencrypt
    - touch /var/lib/letsencrypt/done



- copy:
    dest: /etc/apache2/conf-available/letsencrypt.conf
    content: |

      Alias /.well-known/acme-challenge/ "/var/lib/letsencrypt/.well-known/acme-challenge/"
      <Directory "/var/lib/letsencrypt/">
          AllowOverride None
          Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
          Require method GET POST OPTIONS
      </Directory>


- copy:
    dest: /etc/apache2/conf-available/ssl-params.conf
    content: |
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
      SSLHonorCipherOrder     off
      SSLSessionTickets       off

      SSLUseStapling On
      SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"

      Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
      Header always set X-Frame-Options SAMEORIGIN
      Header always set X-Content-Type-Options nosniff

      SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"



- command: "{{item}}"
  args:
    creates:  /var/lib/letsencrypt/done2
  with_items:
    - a2enconf letsencrypt
    - a2enconf ssl-params
    - touch /var/lib/letsencrypt/done2

  notify: reload-apache2


- apt: name=certbot

# do manually. after config.
# certbot certonly --agree-tos --email admin@julian1.io --webroot -w /var/lib/letsencrypt/ -d julian1.io -d www.julian1.io

# think cron job is *not* run,
# /etc/cron.d/certbot
# instead, there's a systemd certbot service and timer here,
#  /lib/systemd/system/certbot.service
#  /lib/systemd/system/certbot.timer

# 
# certbot renew --dry-run


- copy:
    dest: /lib/systemd/system/certbot.service
    # backup original,
    backup: yes
    content: |
      [Unit]
      Description=Certbot
      Documentation=file:///usr/share/doc/python-certbot-doc/html/index.html
      Documentation=https://letsencrypt.readthedocs.io/en/latest/
      [Service]
      Type=oneshot
      # ExecStart=/usr/bin/certbot -q renew
      ExecStart=/usr/bin/certbot -q renew --renew-hook "systemctl reload apache2"
      PrivateTmp=true

  notify: reconfigure-certbot-update



