
- hosts: all
  vars_files:
    - ../../credentials.yml


  roles:
    - name: admin/user
      username: c-lightning
      path: /home/c-lightning
      mode: 0700 

    - name: personal/dotfiles
      tags: dotfiles
      path: /home/c-lightning
      user: c-lightning

    - name: crypto/c-lightning
      build_dir: /home/c-lightning/c-lightning
      user: c-lightning


  tasks:

    # move to c-lighting-config or just into c-lightning.
    - copy:
        dest: /home/c-lightning/c-lightningd.sh
        owner: c-lightning
        group: c-lightning
        mode: 0700
        content: |
          #!/bin/bash
          # deployed by ansible!

          PATH="c-lightning/lightningd/:$PATH"
          PATH="/nix/var/nix/profiles/default/bin/:$PATH"

          lightningd --lightning-dir=data --bitcoin-datadir /home/testnet/data --network=testnet

      tags: config

    - copy:
        dest: /home/c-lightning/cli.sh
        owner: c-lightning
        group: c-lightning
        mode: 0700
        content: |
          #!/bin/bash
          # deployed by ansible!

          PATH="c-lightning/cli/:$PATH"

          lightning-cli --lightning-dir data "$@"

      tags: config


      # ./cli.sh help
      # ./cli.sh getinfo
      # ./cli.sh listfunds

      # need address to open a channel
      # ./cli.sh newaddr



     
 
#version: v1.8.6
 
