
# SO WE DO WANT IT RUNNING IN A SEPERATE ACCOUNT

# ok,  so we can't just run this to create a new user...
# but we can factor the role.

# hang on no. we do have to build lightning. but it's messy to build it twice...
# but would be interesting to test whether it works.

# change name path to home_dir?
# building services in /usr/local/bin
# that puts them in the path

# ---
# ok, so there's a probem, we can't have two instances running, because we can't bind the port....

# ok - do we want to rebuild before we fund.

# SO WE DO WANT IT RUNNING IN A SEPERATE ACCOUNT

- hosts: all
  vars_files:
    - ../../credentials.yml

  vars:
    user: lightning
    path: /home/lightning
    build_dir: "{{path}}/lightning"

  roles:
    - name: admin/user
      username: "{{user}}"
      mode: 0700

    - name: personal/dotfiles
      tags: dotfiles

    - name: crypto/c-lightning

    - name: crypto/c-lightning-config

