
- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:

  pre_tasks:
    - user: name=monero shell=/bin/bash
    - authorized_key: user=monero key="{{meteo_pubkey}}"
    - file: path=/home/monero mode=0700 state=directory

  roles:
    - name: admin/nodnsupdate
    - name: crypto/monero
      workdir: /home/monero

  tasks:
  
    
