
# solidity should be a different play.
# as should node...

- hosts: all
  vars_files:
    - ../../credentials.yml

  vars:
    # v2.0.5
    # - parity_version: v1.10.8
    # - parity_build_dir: /home/parity/parity-v1.10.8
    - parity_version: v2.0.5
    - parity_build_dir: /home/parity/parity-v2.0.5
    - parity_user: parity

  roles:

    - name: admin/user
      username: parity
      path: /home/parity
      mode: 0700

    # Parity Ethereum requires Rust version 1.29.x to build.
    # version: 1.21.0
    # Version 1.29.1 (2018-09-25)
    - name: devel/rust
      user: parity
      version: 1.29.1


    - name: crypto/parity
      build_dir: "{{parity_build_dir}}"
      version: "{{parity_version}}"
      user: "{{parity_user}}"


    - name: crypto/parity-config
      build_dir: "{{parity_build_dir}}"




