
- hosts: all
  roles:
    - name: misc/rust
      user: meteo

    - name: crypto/parity
      build_dir: /home/meteo/parity
      user: meteo

    # move this somewhere else
    # - misc/node
    # - crypto/web3

