
# see nodes/crypto/parity-test instead...
# important

- hosts: all
  vars_files:
    - ../../credentials.yml

  pre_tasks:

    - user: name=parity shell=/bin/bash

    - authorized_key: user=parity key="{{meteo_pubkey}}"

    - file: path=/home/parity mode=0700 state=directory


  roles:
    - name: misc/rust
      user: parity

    - name: crypto/parity
      build_dir: /home/parity/parity
      user: parity

    # see web3 play
    # - misc/node
    # - crypto/web3

  tasks:
    - copy:
        dest: /home/parity/vars.inc
        content: |
          # deployed by ansible!

          PATH="$HOME/parity/target/release:$PATH"
          PATH="$HOME/node-v6.11.0-linux-x64/bin:$PATH"
          PATH="$HOME/solidity/build/solc:$PATH"
          PATH="$HOME/solidity/build/lllc:$PATH"

          export PATH
      tags: path

