
  - name: restart-eth0
    command: sh -c "/sbin/ifdown eth0 && /sbin/ifup eth0"

  - name: restart-dhcp
    service: name=isc-dhcp-server state=restarted

  - name: reload-sysctl
    command: /sbin/sysctl -p /etc/sysctl.conf



