
# https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep
# https://www.pcsuggest.com/show-notification-play-sound-low-battery-linux/

# /sys/class/power_supply/BAT0/status
# Charging


- copy:
    dest: /usr/local/bin/low-battery-alert.sh
    mode: 0777
    owner: me
    group: me
    src: ../../roles/personal/scripts/files/low-battery-alert.sh


# use cron instead of systemd because for less noisy logs.
# format in /etc/cron.d/ is different than # /var/spool/cron/crontabs/meteo
# /etc/cron.d includes the user
# run once every minute

# note. there is no need to restart cron, at least when changing file content.

# "To keep the output, put the command in a script, and pipe stdout and stderr
# to logger. For example, yourCommand >/dev/null 2>&1 | logger -t mycmd. This
# will put the output in syslog for safe keeping, and stop the MTA complaints"

# TODO would be better to run as another user. ie not me
- copy:
    dest: /etc/cron.d/low-battery-alert
    owner: root
    group: root
    mode: 0644
    content: |
      * * * * * me /usr/local/bin/low-battery-alert.sh 2>&1 | logger -t low-battery-alert







#  - copy:
#      dest: /var/spool/cron/crontabs/meteo
#      owner: meteo
#      group: crontab
#      mode: 0600
#      content: |
# 


#
#   systemd is noisy in syslog and difficult to filter
#  - copy:
#      dest: /etc/systemd/system/low-battery-alert.service
#      mode: 0644
#      content: |
#        # deployed by ansible!
#
#        [Unit]
#        Description=Send alerts on low battery
#
#        [Service]
#        # Type=forked
#        Type=simple
#        # TODO  change me!
#        User=root
#        # User=meteo
#        # Group=meteo
#        ExecStart=/bin/bash /home/meteo/low-battery-alert.sh
#        # Environment="DISPLAY=:0" "XAUTHORITY=/home/b00m/.Xauthority"
#        Restart=always
#        RestartSec=60
#
#        [Install]
#        WantedBy=multi-user.target
#
#    notify: reconfigure-low-battery-alert
#
