
# https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep
# https://www.pcsuggest.com/show-notification-play-sound-low-battery-linux/

# /sys/class/power_supply/BAT0/status
# Charging

  - copy:
      dest: /home/meteo/low-battery-alert.sh
      owner: root
      group: root
      mode: 0744
      content: |
        # deployed by ansible!

        threshold=90
        capacity=$(cat /sys/class/power_supply/BAT0/capacity)
        status=$(cat /sys/class/power_supply/BAT0/status)

        beep() {
          # $1 duration in seconds, $2 freq
          timeout -k ${1}s ${1}s speaker-test --frequency ${2} --test sine 2> /dev/null
        }

        echo "$(date) whoami=$(whoami), status=$status, threshold=$threshold, capacity=$capacity" \
          >> /home/meteo/battery_low.log

        if [ $capacity -le $threshold ] && [ $status != "Charging" ] ; then
          beep 0.1 500
        fi


  - copy:
      dest: /etc/systemd/system/low-battery-alert.service
      mode: 0644
      content: |
        # deployed by ansible!

        [Unit]
        Description=Send alerts on low battery

        [Service]
        # Type=forked
        Type=simple
        # TODO  change me!
        User=root
        # User=meteo
        # Group=meteo
        ExecStart=/bin/bash /home/meteo/low-battery-alert.sh
        # Environment="DISPLAY=:0" "XAUTHORITY=/home/b00m/.Xauthority"
        Restart=always
        RestartSec=60

        [Install]
        WantedBy=multi-user.target

    notify: reconfigure-low-battery-alert


