# https://www.pcsuggest.com/show-notification-play-sound-low-battery-linux/

# /sys/class/power_supply/BAT0/status
# Charging

# deploy script
- copy:
    dest: /usr/local/bin/low-battery-alert.sh
    mode: 0777
    owner: me
    group: me
    src: low-battery-alert.sh



################################
# systemd timer service needs two files. one for service and one for timer.
# Use this to see timers, show how long to run.
#   systemctl list-timers
#   journalctl -f -u low-battery-alert

# https://medium.com/horrible-hacks/using-systemd-as-a-better-cron-a4023eea996d

- copy:
    dest: /etc/systemd/system/low-battery-alert.service
    mode: 0644
    content: |
      # deployed by ansible!

      [Unit]
      Description=Send alerts on low battery

      [Service]
      ExecStart=/bin/bash /usr/local/bin/low-battery-alert.sh

      # this suppresses logging, but not the start message on timer events
      # https://serverfault.com/questions/838574/how-to-silent-a-systemd-service
      #StandardOutput=null
      #StandardError=journal

      [Install]
      WantedBy=timers.target

  notify: reconfigure-low-battery-alert

- copy:
    dest: /etc/systemd/system/low-battery-alert.timer
    mode: 0644
    content: |
      # deployed by ansible!

      [Unit]
      Description=Send alerts on low battery
      Requires=low-battery-alert.service

      [Timer]
      Unit=low-battery-alert.service
      OnUnitInactiveSec=60s
      #RandomizedDelaySec=60s
      AccuracySec=1s

      [Install]
      WantedBy=timers.target


  notify: reconfigure-low-battery-alert




# configure using cron
# use cron instead of systemd because for less noisy logs.
# format in /etc/cron.d/ is different than # /var/spool/cron/crontabs/meteo
# /etc/cron.d includes the user
# run once every minute

# note. there is no need to restart cron, at least when changing file content.

# "To keep the output, put the command in a script, and pipe stdout and stderr
# to logger. For example, yourCommand >/dev/null 2>&1 | logger -t mycmd. This
# will put the output in syslog for safe keeping, and stop the MTA complaints"

# TODO would be better to run as another user. ie not me
#- copy:
#    dest: /etc/cron.d/low-battery-alert
#    owner: root
#    group: root
#    mode: 0644
#    content: |
#      * * * * * me /usr/local/bin/low-battery-alert.sh 2>&1 | logger -t low-battery-alert



