
# https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep
# https://www.pcsuggest.com/show-notification-play-sound-low-battery-linux/

# /sys/class/power_supply/BAT0/status
# Charging

  - copy:
      dest: /home/meteo/low-battery-alert.sh
      # must be meteo!!!
      owner: meteo
      group: meteo
      mode: 0755
      content: |
        #!/bin/bash
        # deployed by ansible!

        threshold=90
        capacity=$(cat /sys/class/power_supply/BAT0/capacity)
        status=$(cat /sys/class/power_supply/BAT0/status)

        beep() {
          # $1 duration in seconds, $2 freq
          timeout -k ${1}s ${1}s speaker-test --frequency ${2} --test sine 2> /dev/null
        }

        echo "$(date) whoami=$(whoami), status=$status, threshold=$threshold, capacity=$capacity" \
          >> /home/meteo/low-battery.log

        if [ $capacity -le $threshold ] && [ $status != "Charging" ] ; then
          beep 0.1 500
        fi

    tags: whoot


  # use cron instead of systemd because for less noisy logs.
  # oK. this works. But why doesn't it work when put in /etc/cron.d ?

#  - copy:
#      dest: /var/spool/cron/crontabs/meteo 
#      owner: meteo
#      group: crontab
#      mode: 0600
#      content: |
#        * * * * * /home/meteo/low-battery-alert.sh

  # format in /etc/cron.d/ is different than # /var/spool/cron/crontabs/meteo 
  # /etc/cron.d includes the user
  - copy:
      dest: /etc/cron.d/low-battery-alert
      owner: root
      group: root
      mode: 0644
      content: |
        * * * * * meteo /home/meteo/low-battery-alert.sh


#
#   systemd is noisy in syslog and difficult to filter
#  - copy:
#      dest: /etc/systemd/system/low-battery-alert.service
#      mode: 0644
#      content: |
#        # deployed by ansible!
#
#        [Unit]
#        Description=Send alerts on low battery
#
#        [Service]
#        # Type=forked
#        Type=simple
#        # TODO  change me!
#        User=root
#        # User=meteo
#        # Group=meteo
#        ExecStart=/bin/bash /home/meteo/low-battery-alert.sh
#        # Environment="DISPLAY=:0" "XAUTHORITY=/home/b00m/.Xauthority"
#        Restart=always
#        RestartSec=60
#
#        [Install]
#        WantedBy=multi-user.target
#
#    notify: reconfigure-low-battery-alert
#
