# should be run as user meteo

  - get_url: > 
      url='https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init'                
      dest=~/rustup-init
      mode=755

  - command: >
      ~/rustup-init -y

  # put in scripts? 
  # PATH="~/.cargo/bin/:$PATH"
