
# install rust to top level dir

  # we need to pass the url, so may as well just install locally here... 
  - get_url: > 
      url='https://sh.rustup.rs'                
      dest=/home/{{rust.user}}/rustup-init
      mode=755
    
  - apt: name=curl
  - apt: name=sudo


    # Note, this will update bash_profile, /home/rust/.cargo/bin/rustc
  - name: rustup
    become: yes
    become_user: "{{rust.user}}"
    command: > 
      /home/{{rust.user}}/rustup-init -y
      creates=/home/{{rust.user}}/.rustup/settings.toml


  # not idempotent, must use shell, because command doesn't work with env
  - name: rustup update
    become: yes
    become_user: "{{rust.user}}"
    shell: > 
      export PATH=/home/{{rust.user}}/.cargo/bin:$PATH && rustup update

