

# should just use the nix pkg?

# v0.14.1

  - debug: msg="user={{user}}, build_dir={{build_dir}}  version={{version}}"


  # key_file=/home/user/.ssh/id_rsa.github-{{ item.repo }}

# not good... should be just using home...
#
#  - copy:
#      dest: /home/{{user}}/cli.sh
#      mode: 0755
#      content: |
#        #!/bin/bash
#        ./bitcoin/src/bitcoin-cli -datadir=./data "$@"
#
#  - copy:
#      dest: /home/{{user}}/start.sh
#      mode: 0755
#      content: |
#        #!/bin/bash
#        ./bitcoin/src/bitcoind -datadir=./data  -txindex



  # https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md
  - apt: name=build-essential
  - apt: name=libtool
  - apt: name=autotools-dev
  - apt: name=automake
  - apt: name=pkg-config
  - apt: name=libssl-dev
  - apt: name=libevent-dev
  - apt: name=bsdmainutils

  # needed for become
  - apt: name=sudo


  # boost
  - apt: name=libboost-system-dev
  - apt: name=libboost-filesystem-dev
  - apt: name=libboost-chrono-dev
  - apt: name=libboost-program-options-dev
  - apt: name=libboost-test-dev
  - apt: name=libboost-thread-dev


  # do checkout as unpriviledged user
  - git:
      repo: "http://github.com/bitcoin/bitcoin"
      dest: "{{build_dir}}"
      accept_hostkey: yes
      force: yes
      recursive: no
      version: "{{version}}"
    become: yes
    become_user: "{{user}}"
    tags: whoot




  # changing all the permissions like this is horrible
  # might be nicer to not have this
  #- file: path="{{build_dir}}" state=directory owner="{{user}}" group="{{user}}" recurse=yes

# git doesn't support become and become_user
#      become=yes
#      become_user="{{user}}"


  # bdb
  - copy:
      dest: "{{build_dir}}/build-bd.sh"
      mode: 0755
      content: |
        # deployed by ansible!

        # not tested
        set -e

        BITCOIN_ROOT=$(pwd)

        # Pick some path to install BDB to, here we create a directory within the bitcoin directory
        BDB_PREFIX="${BITCOIN_ROOT}/db4"
        mkdir -p $BDB_PREFIX

        # Fetch the source and verify that it is not tampered with
        wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
        echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef  db-4.8.30.NC.tar.gz' | sha256sum -c
        # -> db-4.8.30.NC.tar.gz: OK
        tar -xzvf db-4.8.30.NC.tar.gz

        # Build the library and install to our prefix
        cd db-4.8.30.NC/build_unix/
        #  Note: Do a static build so that it can be embedded into the executable, instead of having to find a .so at runtime
        ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX
        make install

    tags: whoot


  - name: build bdb
    shell: creates=db4/lib/libdb.a chdir={{build_dir}} {{item}}
    become: yes
    become_user: "{{user}}"
    with_items:
      - ./build-bd.sh
    tags: whoot


  - name: autogen and configure
    shell: creates=Makefile chdir={{build_dir}} {{item}}
    become: yes
    become_user: "{{user}}"
    with_items:
      - echo doing autogen
      - ./autogen.sh
      - ./configure LDFLAGS="-L$(pwd)/db4/lib/" CPPFLAGS="-I$(pwd)/db4/include/" --disable-shared --without-gui --without-miniupnpc
    tags: whoot


  - name: make bitcoin
    shell: creates=src/bitcoind chdir={{build_dir}} {{item}}
    become: yes
    become_user: "{{user}}"
    with_items:
      - make
    tags: whoot

