

  # install repo sources
  - set_fact: mirror=http://mirror.internode.on.net/pub/debian
  - set_fact: version=stretch
  # - set_fact: upgrade=safe

  - name: copying sources.list 
    copy:
      dest: /etc/apt/sources.list 
      mode: 0644
      content: |
        # deployed by ansible!
        deb {{mirror}} {{version}} main
        deb-src {{mirror}} {{version}} main

        deb http://security.debian.org/ {{version}}/updates main
        deb-src http://security.debian.org/ {{version}}/updates main

        deb {{mirror}} {{version}}-updates main
        deb-src {{mirror}} {{version}}-updates main

        # firmware
        # deb http://http.us.debian.org/debian/ {{version}} non-free contrib
        deb {{mirror}} {{version}} non-free contrib


