#!/bin/bash -e

# echo the phone needs a different dest each time, if clear old photes because it resets the DSC count at 0
# 

#jmtpfs mnt/phone/

#dir="/home/meteo/mnt/drive/Pictures/phone/$( date --rfc-3339=date )"
dir="/home/meteo/mnt/drive/Pictures/phone/xz1"


[ -d $dir ] || mkdir $dir 


# xz1 android 9
rsync -avP "mnt/phone/Internal shared storage/DCIM"  "$dir"



