

# Note bug installing latest,
# https://ethereum.stackexchange.com/questions/23444/getting-error-while-trying-to-install-web3
# npm install web3@0.20.0

# better to have this here, than mixed up with parity 

# creates node_modules - so needs to be non-root user...

- name: install web3
  shell: >
    export PATH=/home/{{user}}/node-v6.11.0-linux-x64/bin:$PATH && npm install web3@0.20.0
  args:
    chdir: /home/{{user}}
    creates: web3
  become: yes
  become_user: "{{user}}"



- copy:
    dest: /home/{{user}}/blockNumber.js 
    content: |
      Web3 = require("web3")
      web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
      console.log( web3.eth.blockNumber )

