
# install minimal user and environment
# eg. ansible-playbook plays/meteo.yml -i parity, -u admin -s


- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  pre_tasks:
    - user: name=meteo shell=/bin/bash
    - authorized_key: user=meteo key="{{meteo_pubkey}}"
    - file: path=/home/meteo mode=0700 state=directory

  roles:
    # - name: admin/timezone
    # - name: admin/locale
    - admin/devenv-lite
    - dotfiles
    - vim

