

# install generic minimal user and environment for server
# eg. ansible-playbook plays/meteo.yml -i parity, -u admin -s

# need sudo and pass, issue that may want other groups than just sudo so cannot make generic

- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  pre_tasks:
    - user: name=meteo shell=/bin/bash
    - authorized_key: user=meteo key="{{meteo_pubkey}}"
    - file: path=/home/meteo mode=0700 state=directory

  roles:
    - name: admin/sshd
    - name: admin/timezone
    - name: admin/locale
    - admin/devenv-lite

    - name: dotfiles
      tags: root_dotfiles
      dotfile_path: /root
      vim_user: root


    - name: dotfiles
      tags: dotfiles
      dotfile_path: /home/meteo
      vim_user: meteo


    - name: pathogen
      tags: pathogen
      vim_path: /home/meteo
      vim_user: meteo


