
    # apt
    - copy:
        dest: /etc/apt/sources.list
        content: |
          # deployed by ansible!

          deb {{mirror}} stretch main contrib non-free
          deb-src {{mirror}} stretch main contrib non-free

          deb http://security.debian.org/debian-security stretch/updates main contrib non-free
          deb-src http://security.debian.org/debian-security stretch/updates main contrib non-free

          # stretch-updates, previously known as 'volatile'
          deb {{mirror}} stretch-updates main contrib non-free
          deb-src {{mirror}} stretch-updates main contrib non-free

      tags: whoot
      # notify...


