
# Also, see play for other roles, - timezone, locale, sshd, fail2ban plays,

# TODO move to node specific role

# needs the following DNS records - MX, A, SPF, PTR (via host), TXT (same as SPF)
# julian1.io
#   MX 10 mail.julian1.io - - 60
#   SPF "v=spf1 mx -all" - - 60
#   TXT "v=spf1 mx -all" - - 60

# _dmarc.julian1.io
#   TXT  "v=DMARC1; p=quarantine; rua=mailto:dmarc@julian1.io; ruf=mailto:dmarc@julian1.io; fo=0; adkim=r; aspf=r; pct=100; rf=afrf; ri=86400"
#
# mail._domainkey.julian1.io
#   TXT  "v=DKIM1; h=sha256; k=rsa; " "p=... " "..."
#
# mail
#   A n.n.n.n  - - 60
#
# (host provider)
#   PTR

# check with, https://www.mail-tester.com/

# TODO maybe move logging out of /var/log/syslog.


# $ netstat -tnlp
# Active Internet connections (only servers)
# Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
# tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      13433/master
# tcp        0      0 127.0.0.1:12301         0.0.0.0:*               LISTEN      728/opendkim
# tcp        0      0 127.0.0.1:54321         0.0.0.0:*               LISTEN      691/opendmarc
# tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      13228/sshd
# tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      13433/master
# tcp        0      0 127.0.0.1:12345         0.0.0.0:*               LISTEN      716/dovecot
# tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      716/dovecot
# tcp6       0      0 :::587                  :::*                    LISTEN      13433/master
# tcp6       0      0 :::25                   :::*                    LISTEN      13433/master
# tcp6       0      0 :::993                  :::*                    LISTEN      716/dovecot


  ##############################################
  # postfix

  - apt: name=postfix

  - apt: name=postfix-policyd-spf-python

  - copy:
      dest: /etc/postfix/main.cf
      content: |
        # deployed by ansible!

        # JA
        # set myhostname, in case the machine name isn't set to a fully-qualified domain name
        myhostname = mail.julian1.io

        # JA
        # not sure if used, or convenience var
        mydomain = julian1.io

        # The myorigin parameter specifies the domain that appears in mail that is posted
        # on this machine. The default is to use the local machine name, $myhostname,
        # which defaults to the name of the machine. Unless you are running a really
        # small site, you probably want to change that into $mydomain,
        myorigin = julian1.io

        # JA not used
        alias_maps = hash:/etc/aliases
        alias_database = hash:/etc/aliases

        # JA
        # The mydestination parameter specifies what domains this machine will deliver locally,
        mydestination = $myhostname, $mydomain, localhost

        relayhost =
        # mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
        mynetworks = 127.0.0.0/8
        mailbox_size_limit = 0
        recipient_delimiter = +
        inet_interfaces = all
        inet_protocols = all


        # JA catchall
        # https://serverfault.com/questions/23717/postfix-how-do-you-redirect-all-emails-to-one-user-eg-example-com-%E2%86%92-userex
        luser_relay = meteo@julian1.io
        local_recipient_maps =


        # Debian specific:  Specifying a file name will cause the first
        # line of that file to be used as the name.  The Debian default
        # is /etc/mailname.
        #myorigin = /etc/mailname

        smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
        biff = no

        # appending .domain is the MUA's job.
        append_dot_mydomain = no

        # Uncomment the next line to generate "delayed mail" warnings
        #delay_warning_time = 4h

        readme_directory = no

        # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
        # fresh installs.
        compatibility_level = 2

        # JA https://www.reddit.com/r/selfhosted/comments/4pi5r1/how_to_send_email_encrypted/
        # http://www.postfix.org/TLS_README.html
        smtp_tls_security_level = may

        # TLS parameters
        # TODO not signed by CA presents MITM problem for clients
        # https://askubuntu.com/questions/396120/what-is-the-purpose-of-the-ssl-cert-snakeoil-key
        # https://superuser.com/questions/700170/are-ssls-default-snake-oil-certificates-truly-snake-oil-as-opposed-to-being-gen
        smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
        smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        smtpd_use_tls=yes

        # JA TODO CHECK THIS - what is data_directory?
        smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
        smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

        # See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
        # information on enabling SSL in the smtp client.

        # JA required, not just cyrus or dovecot sasl access to smtpd
        smtpd_sasl_auth_enable = yes

        # JA
        # smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
        smtpd_recipient_restrictions =
           permit_mynetworks
           permit_sasl_authenticated
           reject_unauth_destination
           check_policy_service unix:private/policy-spf

        # JA Dovecot
        # sasl type
        # http://www.postfix.org/SASL_README.html#server_sasl_enable
        # https://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL
        smtpd_sasl_type = dovecot

        # for postfix/ dovecot smtp communication. use tcp instead of domain socket to be consistent with dkim and dmarc
        smtpd_sasl_path = inet:127.0.0.1:12345


        # JA SPF
        policy-spf_time_limit = 3600s

        # JA DKIM
        # https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy
        milter_protocol = 2
        milter_default_action = accept

        # JA DKIM and DMARC services
        smtpd_milters = inet:localhost:12301,inet:localhost:54321
        non_smtpd_milters = inet:localhost:12301,inet:localhost:54321

        # JA
        header_checks = regexp:/etc/postfix/header_checks


    # restart
    notify: reconfigure-postfix
    tags: postfix


  ##############################################
  # SPF see,
  #   https://help.ubuntu.com/community/Postfix/SPF
  #   https://www.linode.com/docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8
  # $ default configuration, grep -v ^# /etc/postfix/master.cf

  - copy:
      dest: /etc/postfix/master.cf
      content: |
        # deployed by ansible!
        smtp      inet  n       -       y       -       -       smtpd
        pickup    unix  n       -       y       60      1       pickup
        cleanup   unix  n       -       y       -       0       cleanup
        qmgr      unix  n       -       n       300     1       qmgr
        tlsmgr    unix  -       -       y       1000?   1       tlsmgr
        rewrite   unix  -       -       y       -       -       trivial-rewrite
        bounce    unix  -       -       y       -       0       bounce
        defer     unix  -       -       y       -       0       bounce
        trace     unix  -       -       y       -       0       bounce
        verify    unix  -       -       y       -       1       verify
        flush     unix  n       -       y       1000?   0       flush
        proxymap  unix  -       -       n       -       -       proxymap
        proxywrite unix -       -       n       -       1       proxymap
        smtp      unix  -       -       y       -       -       smtp
        relay     unix  -       -       y       -       -       smtp
        showq     unix  n       -       y       -       -       showq
        error     unix  -       -       y       -       -       error
        retry     unix  -       -       y       -       -       error
        discard   unix  -       -       y       -       -       discard
        local     unix  -       n       n       -       -       local
        virtual   unix  -       n       n       -       -       virtual
        lmtp      unix  -       -       y       -       -       lmtp
        anvil     unix  -       -       y       -       1       anvil
        scache    unix  -       -       y       -       1       scache
        maildrop  unix  -       n       n       -       -       pipe
          flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
        uucp      unix  -       n       n       -       -       pipe
          flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
        ifmail    unix  -       n       n       -       -       pipe
          flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
        bsmtp     unix  -       n       n       -       -       pipe
          flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
        scalemail-backend unix  -       n       n       -       2       pipe
          flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
        mailman   unix  -       n       n       -       -       pipe
          flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
          ${nexthop} ${user}

        # JA SPF
        policy-spf  unix  -       n       n       -       -       spawn
          user=nobody argv=/usr/bin/policyd-spf

        # JA port 587
        # https://www.faqforge.com/linux/how-to-enable-port-587-submission-in-postfix/
        #submission inet n - n - - smtpd
        # https://serverfault.com/questions/481477/in-postfix-how-to-enforce-tls-auth-over-587-while-leaving-tls-optional-for-25

        submission inet n       -       n       -       -       smtpd
          -o smtpd_tls_security_level=encrypt


        # https://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL
        # these work as overrides - note that many are repeated

        # -o smtpd_sasl_path=private/auth
        #        submission inet n - n - - smtpd
        #          -o smtpd_tls_security_level=encrypt
        #          -o smtpd_sasl_auth_enable=yes
        #          -o smtpd_sasl_type=dovecot
        #          -o smtpd_sasl_security_options=noanonymous
        #          -o smtpd_sasl_local_domain=$myhostname
        #          -o smtpd_client_restrictions=permit_sasl_authenticated,reject
        #          -o smtpd_sender_login_maps=hash:/etc/postfix/virtual
        #          -o smtpd_sender_restrictions=reject_sender_login_mismatch
        #          -o smtpd_recipient_restrictions=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject


    # reconfigure and restart handler
    notify: reconfigure-postfix
    tags: postfix



  ##############################################
  # DKIM

  # NOte, that we are not generating restart events for all actions, so potentially need manual restart of dkim
  # checking dns record,
  #  dig google._domainkey.protodave.com TXT
  #  dig mail._domainkey.julian1.io TXT
  # note that p really is in two parts,

  - apt: name=opendkim
  - apt: name=opendkim-tools   # for signing tool,


  # https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy
  - copy:
      dest: /etc/opendkim.conf
      content: |
        # deployed by ansible!

        AutoRestart             Yes
        AutoRestartRate         10/1h
        UMask                   002
        Syslog                  yes
        SyslogSuccess           Yes
        LogWhy                  Yes

        Canonicalization        relaxed/simple

        ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
        InternalHosts           refile:/etc/opendkim/TrustedHosts
        KeyTable                refile:/etc/opendkim/KeyTable
        SigningTable            refile:/etc/opendkim/SigningTable

        Mode                    sv
        PidFile                 /var/run/opendkim/opendkim.pid
        SignatureAlgorithm      rsa-sha256

        UserID                  opendkim:opendkim

        Socket                  inet:12301@localhost
    # restarts it
    notify: reconfigure-dkim
    tags: whoot


  - copy:
      dest: /etc/default/opendkim
      content: |
        # deployed by ansible!

        #DAEMON_OPTS=""
        RUNDIR=/var/run/opendkim
        # JA
        SOCKET="inet:12301@localhost"
        USER=opendkim
        GROUP=opendkim
        PIDFILE=$RUNDIR/$NAME.pid
        EXTRAAFTER=

    # restarts it
    notify: reconfigure-dkim
    tags: whoot


  - file: path=/etc/opendkim        state=directory owner=root group=opendkim
  - file: path=/etc/opendkim/keys   state=directory owner=root group=opendkim


  - copy:
      dest: /etc/opendkim/TrustedHosts
      content: |
        # deployed by ansible!

        127.0.0.1
        localhost
        192.168.0.1/24

        *.julian1.io

  - copy:
      dest: /etc/opendkim/KeyTable
      content: |
        # deployed by ansible!

        mail._domainkey.julian1.io julian1.io:mail:/etc/opendkim/keys/julian1.io/mail.private

  - copy:
      dest: /etc/opendkim/SigningTable
      content: |
        # deployed by ansible!

        *@julian1.io mail._domainkey.julian1.io


  - file: path=/etc/opendkim/keys/julian1.io   state=directory owner=root group=opendkim


  # generate keys
  - command: opendkim-genkey -s mail -d julian1.io
    args:
      chdir:  /etc/opendkim/keys/julian1.io
      creates: mail.private


  - file: path=/etc/opendkim/keys/julian1.io/mail.private     owner=opendkim group=root



  ##############################################
  # Dmarc

  # https://www.skelleton.net/2015/03/21/how-to-eliminate-spam-and-protect-your-name-with-dmarc/#dmarc


  # The DMARC record is a txt record for the host “_dmarc.example.com”.

    # non-privileged user
  - user: name=dmarc shell=/bin/bash

  - apt: name=opendmarc

  - copy:
      dest: /etc/opendmarc.conf
      content: |
        # deployed by ansible!

        AuthservID mail.julian1.io  # JA
        # PidFile /var/run/opendmarc.pid #Debian default

        # JA mar 10 2021
        # changed, due to inability to write
        PidFile /var/run/opendmarc/opendmarc.pid



        RejectFailures false
        Syslog true

        TrustedAuthservIDs mail.julian1.io   # JA
        UMask 0002
        UserID opendmarc:opendmarc
        IgnoreHosts /etc/opendmarc/ignore.hosts
        HistoryFile /var/run/opendmarc/opendmarc.dat
        #for testing:
        SoftwareHeader true
  
        # JA mar 10 2021
        # https://serverfault.com/questions/1026200/opendkim-wont-start-opendkim-milter-socket-must-be-specified
        Socket                  inet:54321@localhost

  - file: path=/etc/opendmarc/ state=directory owner=root group=opendmarc

  - copy:
      dest: /etc/opendmarc/ignore.hosts
      content: |
        # deployed by ansible!

        localhost


  # seems like is overriding the socket environment variable
  # bug on debian stretch,
  # bug affects dkim and stretch,
  # https://unix.stackexchange.com/questions/351584/how-to-configure-the-socket-for-opendkim-on-debian-testing-stretch
  # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864162
  - copy:
      dest: /lib/systemd/system/opendmarc.service
      content: |
        # deployed by ansible!

        [Unit]
        Description=OpenDMARC Milter
        Documentation=man:opendmarc(8) man:opendmarc.conf(5)
        After=network.target nss-lookup.target

        [Service]
        Type=forking
        PIDFile=/var/run/opendmarc/opendmarc.pid
        User=opendmarc
        # JA ExecStart=/usr/sbin/opendmarc -p local:/var/run/opendmarc/opendmarc.sock  -u opendmarc -P /var/run/opendmarc/opendmarc.pid
        # it already reads its environment from /etc/default/opendmarc...
        ExecStart=/usr/sbin/opendmarc
        Restart=on-failure
        ExecReload=/bin/kill -USR1 $MAINPID

        [Install]
        WantedBy=multi-user.target



    notify: reconfigure-dmarc

      # TODO after modifying service file, need to run, systemctl daemon-reload


  - copy:
      dest: /etc/default/opendmarc
      content: |
        # deployed by ansible!

        # DAEMON_OPTS=""
        RUNDIR=/var/run/opendmarc
        # JA
        SOCKET="inet:54321@localhost"
        USER=opendmarc
        GROUP=opendmarc
        PIDFILE=$RUNDIR/$NAME.pid
        EXTRAAFTER=
    notify: reconfigure-dmarc





  ##############################################
  # Dovecot
  # https://www.digitalocean.com/community/tutorials/how-to-set-up-a-postfix-e-mail-server-with-dovecot

  - apt: name=dovecot-core
    tags: dovecot

  - apt: name=dovecot-imapd
    tags: dovecot

  # for all the default packages,
  # - apt: name=dovecot-common

  # disable port 143 - unencrypted...
  # pam is localpasswords

  - copy:
      dest: /etc/dovecot/dovecot.conf
      backup: yes
      content: |
        # deployed by ansible!

        # JA The "plaintext" authentication will be tunneled through TLS
        disable_plaintext_auth = no
        mail_privileged_group = mail
        mail_location = mbox:~/mail:INBOX=/var/mail/%u
        userdb {
          driver = passwd
        }
        passdb {
          args = %s
          driver = pam
        }
        protocols = " imap"


        ssl=required
        # ssl_cert = </etc/ssl/certs/mailcert.pem
        # ssl_key = </etc/ssl/private/mail.key

        ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
        ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key


        # JA communciation with postfix, tcp rather than domain socket, to be consistent with dkim and dmarc
        service auth {
          inet_listener {
            address=127.0.0.1
            port = 12345
          }
        }


        # support imaps only, disable imap
        service imap-login {
          inet_listener imap {
            port = 0
          }
          inet_listener imaps {
            port = 993
          }
        }

    notify: reconfigure-dovecot
    tags: dovecot


  ##############################################
  # aliases
  # TODO alias https://www.digitalocean.com/community/tutorials/how-to-set-up-a-postfix-e-mail-server-with-dovecot
  # we redirect 'mail' user here,

  # this is a simple way to create service specific users, while redirecting to a 'generic' user, so no pam entry is needed
  # also avoids a generic catchall, which will fail against script attacks

  # not sure this this works or is needed with generic catchall, or empty, local_recipient_maps =
  # but leave in case of catchall revert,

  - copy:
      dest: /etc/aliases
      backup: yes
      content: |
        # deployed by ansible!

        mailer-daemon: postmaster
        postmaster:    root
        # JA
        mail: meteo
        root: meteo
        nobody: root
        hostmaster: root
        usenet: root
        news: root
        webmaster: root
        www: root
        ftp: root
        abuse: root

    notify: reconfigure-aliases
    tags: aliases


  ##############################################
  # header_checks
  # http://www.postfix.org/header_checks.5.html
  # http://mattshaw.org/news/how-to-filter-mail-with-postfix-header_checks/

  # REJECT - sends rejected reply
  # DISCARD - discards silently

  - copy:
      dest: /etc/postfix/header_checks
      content: |
        # deployed by ansible!

        /^From:.*support@gitter.im/           DISCARD
        /^From:.*jobs-noreply@linkedin.com/   DISCARD
        /^From:.*jobs-listings@linkedin.com/  DISCARD

        /^Subject: test rejects 123/          REJECT

        /^From:.*catriona.*/                  REDIRECT mail@julian1.io

        # /^To: bob@here.com/ REDIRECT bob@there.com

    tags: header_checks


