
# so if we set up as tv
# if use jessie ...  need to change the roles - with a pre_task to add the repo...
# should use jessie.
# if testing then we will have to build ourselves.

- hosts: chromebox
  vars_files:
    - ../vars/credentials.yml
  vars:
    - sources_template: tvheadend.j2
    # might be nicer to take from dhcp...
    - hostname: chromebox
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - ../vars/credentials.yml
  roles:
    - debian
    - timezone
    - locale
    - hostname
    - common
    - dotfiles
  tasks:
    - apt: name=pciutils        # lspci
    - apt: name=wpasupplicant
    - apt: name=man

    - apt_key: keyserver=keyserver.ubuntu.com id=379CE192D401AB61

    - apt: name=tvheadend

#    - apt: rtl-sdr

#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61


