
- hosts: geoserver
  vars:
    - user: meteo
    - timezone: Australia/Hobart
    - mirror: http://mirror.internode.on.net/pub/debian
    - template: debian.j2
    - version: jessie
    - upgrade: safe

  roles:
    - debian
    - timezone
    - basic
    - geoserver
  

  tasks:
#    - include: >
#        ../roles/distribution/tasks/main.yml
#        mirror=http://mirror.internode.on.net/pub/debian
#        template=debian.j2
#        version=jessie
#        upgrade=safe

    - include_vars: credentials.yml

    # - include: ../roles/common/tasks/basic.yml
    # - include: basic.yml

    # - include: ../roles/postgres/tasks/main.yml
    # - include: ../roles/geonetwork/tasks/drop-db.yml
    # - include: ../roles/geonetwork/tasks/restore-db.yml

    #- include: ../roles/geoserver/tasks/main.yml
    # - include: ../roles/geoserver/tasks/main.yml

  handlers:
    - include: ../roles/common/handlers/main.yml

