
- hosts: drupal
  vars_files:
    - "{{inventory_dir | dirname}}/credentials.yml"
  vars:
    - users:
      - { name: meteo,    group: adm, pubkey: "{{meteo_pubkey}}" }
  roles:
    - debian
    - timezone
    - locale
    - common
    - dotfiles
  tasks:
    - apt: name=mysql-server
