
# warning rpc client password is easily guessible, and exposed to 127.0.0.1

# run play unpriviledged. only requires path and user

# eg. usage,
# ./cli.sh help
# ./cli.sh getinfo
#
# wallet stuff
# ./cli.sh listreceivedbyaddress 0 true
# ./cli.sh getrawtransaction 'xxx' 1
# ./cli.sh estimatefee 2
# ./cli.sh settxfee 0.0001
# ./cli.sh sendtoaddress aaaa 0.5
# ./cli.sh listtransactions
#
# non-wallet, -txindex - doesn't work.
# a=$( ./cli.sh getrawtransaction 8e43e27eeafe4ca95e6fa712638cf607fc28d01c82493fcf706fc0915733819b )
# ./cli.sh decoderawtransaction $a
# or just,
#  ./cli.sh getrawtransaction 8e43e27eeafe4ca95e6fa712638cf607fc28d01c82493fcf706fc0915733819b 1

- debug: msg="user={{user}}, path={{path}}"

- copy:
    dest: "{{path}}/vars.inc"
    content: |
      # deployed by ansible!
      #
      PATH="{{path}}/bitcoin/src:$PATH"
      export PATH

  tags: config


- file: path={{path}}/data mode=0700 owner={{user}} group={{user}} state=directory

- copy:
    dest: "{{path}}/data/bitcoin.conf"
    content: |
      # deployed by ansible!
      #
      server=1
      rpcuser=test
      rpcpassword=test
      txindex=1


- copy:
    dest: "{{path}}/cli.sh"
    mode: 0755
    content: |
      #!/bin/bash
      # deployed by ansible!

      . ./vars.inc

      #  --rpcuser=test --rpcpassword=test \

      # for local client, specify data dir to read user/password from bitcoin.conf
      bitcoin-cli \
        --datadir=./data $@ 

      # | less


- copy:
    dest: "{{path}}/start-bitcoind.sh"
    mode: 0755
    content: |
      #!/bin/bash
      # deployed by ansible!

      . ./vars.inc

      # passing -txindex doesn't seem to work. maybe needs to be -txindex=1
      # but better to just place in bitcoin.conf
      bitcoind -datadir=./data


