

  # eg. usage, 
  # ./cli.sh getinfo
  # ./cli.sh listreceivedbyaddress 0 true
  # ./cli.sh getrawtransaction 'xxx' 1
  # ./cli.sh estimatefee 2
  # ./cli.sh settxfee 0.0001
  # ./cli.sh sendtoaddress aaaa 0.5
  # /cli.sh  listtransactions

  - copy:
      dest: "{{path}}/cli.sh"
      mode: 0755
      content: |
        #!/bin/bash
        # deployed by ansible!

        bitcoin-cli -datadir=./data -testnet $@ | less


  - copy:
      dest: "{{path}}/bitcoind.sh"
      mode: 0755
      content: |
        #!/bin/bash
        # deployed by ansible!

        bitcoind -datadir=./data -testnet -txindex


  - file: path={{path}}/data mode=0700 owner={{user}} group={{user}} state=directory

  - copy:
      dest: "{{path}}/data/bitcoin.conf"
      content: |
        # deployed by ansible!
        server=1
        rpcuser=test
        rpcpassword=test


