

- apt: name=git

- git: repo=https://github.com/julian1/dotfiles   dest={{path}}/dotfiles


- debug: msg="user={{user}}, path={{path}}"

# need a flag to force update, if git changes,

- command: sh -c "bash -c ./install.sh {{path}}"
  args:
    chdir:        "{{path}}/dotfiles"
    creates:      "{{path}}/.vimrc"






