
# not sure, if shouldn't be a sh scripted install in a separate github repo, since it's more code

# vimrc gets deployed here.
# but pathogen has it's own role


- debug: msg="user={{user}}, path={{path}}"


- copy: src=bash_aliases    dest={{path}}/.bash_aliases

- copy: src=gitconfig       dest={{path}}/.gitconfig

- copy: src=screenrc        dest={{path}}/.screenrc

- copy: src=vimrc           dest={{path}}/.vimrc

# localize vim directories for temp files and pathogen - required for .vimrc
# vim tmp file handling
# http://stackoverflow.com/questions/821902/disabling-swap-files-creation-in-vim
- file: path="{{path}}/{{item}}" state=directory owner={{user}} group={{user}}
  with_items:
    - "/.vim"
    - "/.vim/backup"
    - "/.vim/swap"
    - "/.vim/undo"
    - "/.vim/autoload"
    - "/.vim/bundle"


# make sure  .bashrc really exists
- file: path="{{path}}/.bashrc" state=touch owner={{user}} group={{user}}

# root instance of .bashrc doesn't include .bash_aliases
# not sure about this..
- lineinfile: >
    dest={{path}}/.bashrc
    state=present
    line='. .bash_aliases'
  when: user == "root"


