

FROM debian:stretch

RUN apt-get update
RUN apt-get -y install ansible


# env
ENV       w /root
ENV       a $w/ansible-consolidated


RUN mkdir $a
COPY roles $a/roles
COPY plays $a/plays
COPY ansible.cfg $a/ansible.cfg
# careful, will bake into the image
#COPY credentials.yml $a/credentials.yml

# RUN cd $a && ansible-playbook plays/personal/bootstrap.yml -i localhost, -c local
RUN cd $a && ansible-playbook plays/admin/postgres.yml -i localhost, -c local

WORKDIR   $w

