
- hosts: all
  vars_files:
    - ../../vars/credentials.yml

  pre_tasks:
    - user: name=meteo shell=/bin/bash password={{meteo_password}} groups=sudo
    - file: path=/home/meteo mode=0700 owner=meteo group=meteo state=directory

    - authorized_key: user=meteo key="{{meteo_pubkey}}"

  roles:
    - admin/devenv-lite

    - name: crypto/geth
      build_dir: /home/meteo/
      user: meteo

    - name: misc/node
      deploy_path: /home/meteo

    - name: crypto/web3
      user: meteo

  tasks:

    - copy:
        owner: meteo
        group: meteo
        mode: 400
        dest: /home/meteo/.bash_aliases
        content: |
          # deployed by ansible!

          PATH="$HOME/node-v6.11.0-linux-x64/bin:$PATH"
          PATH="$HOME/go-ethereum/build/bin:$PATH"

          export PATH
      tags: path



#  geth  --maxpeers 0  console 2> /dev/null
#  geth  --maxpeers 0  console


