
# important, we may be able to do a port-forward - for the rpc interface to a parity running in cloud
# or even, iptables to map to infura etc.

- hosts: all
  vars_files:
    - ../../vars/credentials.yml
  vars:

  pre_tasks:
    - user: name=meteo shell=/bin/bash
    - file: path=/home/meteo mode=0700
    - authorized_key: user=meteo key="{{meteo_pubkey}}"

  roles:
    - admin/devenv-lite

    - name: misc/rust
      user: meteo

    - name: crypto/parity
      build_dir: /home/meteo/parity
      user: meteo

    - name: misc/node
      deploy_path: /home/meteo

    - name: crypto/web3
      user: meteo

    #- crypto/geth
    # - crypto/solidity

  tasks:
    - copy:
        dest: /home/meteo/.bash_aliases
        content: |
          # deployed by ansible!

          PATH="$HOME/parity/target/release:$PATH"
          PATH="$HOME/node-v6.11.0-linux-x64/bin/:$PATH"
          export PATH
      tags: path

