
# Note, 1G is not enough mem for the compile.

- hosts: all
  vars_files:
    - ../../vars/credentials.yml
  vars:

  pre_tasks:
    - user: name=meteo shell=/bin/bash
    - file: path=/home/meteo mode=0700 owner=meteo group=meteo state=directory

    - authorized_key: user=meteo key="{{meteo_pubkey}}"


  roles:
    - admin/devenv-lite

    - name: admin/swap
      size: 1000000

    - name: misc/rust
      user: meteo

    - name: crypto/parity
      build_dir: /home/meteo/parity
      user: meteo

    - name: misc/node
      deploy_path: /home/meteo

    - name: crypto/web3
      user: meteo

    - name: crypto/solidity
      user: meteo
      tags: solidity

    #- crypto/geth

  tasks:
    - copy:
        owner: meteo
        mode: 400
        dest: /home/meteo/.bash_aliases
        content: |
          # deployed by ansible!

          PATH="$HOME/parity/target/release:$PATH"
          PATH="$HOME/node-v6.11.0-linux-x64/bin:$PATH"
          PATH="$HOME/solidity/build/solc:$PATH"
          PATH="$HOME/solidity/build/lllc:$PATH"

          PATH="$HOME/.meteor:$PATH"

          export PATH
      tags: path

  # hmmn, if we just set-up a local parity it might work out of the box...

  # did not
  # curl https://install.meteor.com/ | sh
  # npm install  meteor-build-client

