# should be run as user meteo
# note this installs rustup, to do further management

  # assumes rust is installed,

  # needs to be root for all this stuff,
  # gcc, g++, libssl-dev/openssl, libudev-dev and pkg-config
  - apt: name=gcc
  - apt: name=g++
  - apt: name=libssl-dev
  - apt: name=libudev-dev
  - apt: name=pkg-config



  # rustup update

  # put in scripts? 
  # PATH="~/.cargo/bin/:$PATH"

  # download Parity code
# $ git clone https://github.com/paritytech/parity
#$ cd parity

  # build in release mode
  #

  # also need node
