

  # Parity Ethereum also requires gcc, g++, libudev-dev, pkg-config, file, make, and cmake packages to be installed.

  - apt: name=gcc
  - apt: name=g++
  - apt: name=libudev-dev   # old dep, may not need
  - apt: name=pkg-config
  - apt: name=make
  - apt: name=cmake
  # - apt: name=yasm        # doccumented dep, but may not need.


  # old
  #- apt: name=libssl-dev  removal not tested...

  - apt: name=git

  - name: git checkout parity
    git: repo=https://github.com/paritytech/parity
      dest={{build_dir}}
      accept_hostkey=yes
      force=yes
      recursive=no
      version={{version}}
    become: yes
    become_user: "{{user}}"
    tags: checkout


  - name: build parity
    become: yes
    become_user: "{{user}}"
    shell: >
      export PATH="$HOME/.cargo/bin:$PATH" && cargo build --release --features final 2>&1 | tee log.txt
      chdir={{build_dir}}
      creates={{build_dir}}/target/release/parity
    tags: build


# - file: path="{{build_dir}}" state=directory owner="{{user}}" group="{{user}}" recurse=yes

# cargo build --release   <- builds just parity
# cargo build --release --features final


# version=v1.7.12
# version=v1.7.6
# version=v1.6.10
# version=v1.6.8
# there is v1.7.0,but looks bloated
# v2.0.5

