
  # needs to be root for all this stuff,
  # gcc, g++, libssl-dev/openssl, libudev-dev and pkg-config
  - apt: name=gcc
  - apt: name=g++
  - apt: name=libssl-dev
  - apt: name=libudev-dev
  - apt: name=pkg-config

  - apt: name=git

  - name: checkout git parity 
    git: repo=https://github.com/paritytech/parity
      dest={{parity.build_dir}}
      accept_hostkey=yes
      force=yes
      recursive=no
      version=v1.6.8


  - file: path="{{parity.build_dir}}" state=directory owner="{{parity.user}}" group="{{parity.user}}" recurse=yes

  - name: build parity 
    become: yes
    become_user: "{{parity.user}}"
    tags: parity
    shell: > 
      export PATH=/home/parity/.cargo/bin:$PATH && cargo build --release
      chdir={{parity.build_dir}}


  # also need node. handle externally to here...
