
  # see parity play for rust and node etc.
  # note, this differs from monero where everything is in the role, 

  # rust and node and handle in other roles

  # needs to be root for all this stuff,
  # gcc, g++, libssl-dev/openssl, libudev-dev and pkg-config
  - apt: name=gcc
  - apt: name=g++
  - apt: name=libssl-dev
  - apt: name=libudev-dev
  - apt: name=pkg-config

  - apt: name=git

  - name: git checkout parity
    git: repo=https://github.com/paritytech/parity
      dest={{build_dir}}
      accept_hostkey=yes
      force=yes
      recursive=no
      version=v1.7.12
      # version=v1.7.6
      # version=v1.6.10
      # version=v1.6.8
      # there is v1.7.0,but looks bloated
    become: yes
    become_user: "{{user}}"
    tags: checkout


#  - file: path="{{build_dir}}" state=directory owner="{{user}}" group="{{user}}" recurse=yes

  - name: build parity
    become: yes
    become_user: "{{user}}"
    tags: parity
    shell: >
      export PATH="$HOME/.cargo/bin:$PATH" && cargo build --release
      chdir={{build_dir}}
      creates={{build_dir}}/target/release/parity


