
# this is so small it's not valuable in terms of factorization. 
# but it allows user creation to be sequenced in ordinary rolelist, rather than pre_tasks.  

# TODO issue is ability to set groups.

  - user: name={{username}} shell=/bin/bash

  - authorized_key: user={{username}} key="{{meteo_pubkey}}"

  - file: path={{path}} mode={{mode}} state=directory



