
# apu router with wireless ap, vlan trunking, dns/dhcp, multicast-routing, voip, nat, tftp, xmodem serial

  # Use static ip, since if dns goes wrong, we can end up provisioning 127.0.0.1
- hosts: 192.168.100.1
  vars_files:
    - ../../vars/credentials.yml
  vars:
    - hostname: apu
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}", home_dir: /home/meteo }

  roles:
    - admin/apt/testing
    - admin/apt/update
    - admin/timezone
    - admin/locale
    # - hostname
    # - common
    - admin/ip-forwarding
    - dotfiles

  tasks:
    - apt: name=ntp             # network time
    - apt: name=tcpdump
    - apt: name=netstat-nat     # nat connections
    - apt: name=dnsutils        # dig, whois
    - apt: name=wireless-tools  # iwconfig - useful to check wlan0 state
    - apt: name=iw

    - apt: name=pciutils        # lspci
    - apt: name=usbutils        # lsusb
    - apt: name=ethtool

    - apt: name=firmware-ralink # backup AP
    - apt: name=haveged         # entropy for wifi crypto


    # TODO factor into a role if use more than here...
    # sensors
    - apt: name=lm-sensors
    - shell: creates=ansible-lm-sensors {{item}}
      with_items:
        - sensors-detect --auto
        - touch ansible-lm-sensors

    # WARNING: Nasty, after kernel upgrade, was
    # missing wlan0. Have to apt-get purge and
    # reinstall firmware-realtek as it
    # modifies initrd.img

    # Atheros AR9280 and wlan0 should be seen and can do iwlist scan
    - apt: name=firmware-realtek

    - apt: name=hostapd

    # hostapd.conf goes first since referred to by /etc/network/interfaces
    # AP primary
    - copy:
        dest: /etc/hostapd/hostapd-wlan0.conf
        content: |
          # deployed by ansible!
          interface=wlan0
          ssid=AP1
          hw_mode=g
          channel=7
          auth_algs=1
          wpa=2
          wpa_passphrase={{wpa_passphrase}}
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-wlan0

    # AP2
    - copy:
        dest: /etc/hostapd/hostapd-wlan1.conf
        content: |
          # deployed by ansible!
          interface=wlan1
          ssid=AP2
          hw_mode=g
          channel=8
          # remove everything below for open AP
          auth_algs=1
          wpa=2
          wpa_passphrase={{wpa_passphrase}}
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-wlan1

    - copy:
        dest: /etc/network/interfaces
        content: |
          # deployed by ansible!

          # loopback
          auto lo
          iface lo inet loopback

          # wan
          # allow-hotplug eth0
          #   iface eth0 inet dhcp

          # http://www.cyberciti.biz/tips/howto-configure-linux-virtual-local-area-network-vlan.html
          # just had to do /sbin/ifup eth0.100.100
          # VLAN = Third octet of IPv4 subnets, network identifier in IPv6 addresses.

          # vlan 100 switch management
          auto eth0.100
          iface eth0.100 inet static
            address 192.168.100.1
            netmask 255.255.255.0
            vlan-raw-device eth0

          # vlan 120 wan
          auto eth0.120
          iface eth0.120 inet dhcp
            vlan-raw-device eth0

          # vlan 200
          auto eth0.200
          iface eth0.200 inet static
            address 192.168.200.1
            netmask 255.255.255.0
            vlan-raw-device eth0

          # vlan 201
          auto eth0.201
          iface eth0.201 inet static
            address 192.168.201.1
            netmask 255.255.255.0
            vlan-raw-device eth0

          # router management
          # TODO do we need allow-hotplug?
          auto eth1
          iface eth1 inet static
            address 172.16.1.1
            netmask 255.255.255.0

          # AP primary
          auto wlan0
          iface wlan0 inet static
            hostapd /etc/hostapd/hostapd-wlan0.conf
            address 192.168.43.1
            netmask 255.255.255.0
            # gateway to 10.0.0.0 via dell-home
            # TODO A cleaner way to persist routing entries?
            post-up ip route add 10.0.0.0/8 via 192.168.43.14

          # AP 2
          auto wlan1
          iface wlan1 inet static
            hostapd /etc/hostapd/hostapd-wlan1.conf
            address 192.168.44.1
            netmask 255.255.255.0

      notify:
        # will these all be run together
        # TODO - restart networking generally?
        # TODO restart-eth0.100 and 200
        - restart-eth1
        # - restart-eth2
        - restart-wlan0



      # may need to restart wlan0 here? at least when install dnsmasq
    - apt: name=iptables-persistent

    - copy:
        dest: /etc/iptables-rules
        content: |
          # deployed by ansible!
          #####
          # filter
          iptables -t filter --flush
          iptables -t nat --flush
          iptables -t mangle --flush

          #####
          # input default policy
          iptables -P INPUT DROP

          # Incoming from WAN/eth0.120 (TODO state conntrack established, related in forward)
          # TODO remove the 1
          # http responses - required for apt-get update/upgrade
          iptables -I INPUT 1 -p tcp --sport 80 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 443 -j ACCEPT
          # dns responses
          iptables -I INPUT 1 -p udp --sport 53 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 53 -j ACCEPT
          # ping/icmp responses
          iptables -I INPUT 1 -p icmp -j ACCEPT

          # Internal
          # ssh
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 22 -j ACCEPT
          # tftp - port-range is inclusive
          iptables -I INPUT 1 ! -i eth0.120 -p udp --match multiport --dport 69,1024:1034 -j ACCEPT
          # dns
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 53 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 53 -j ACCEPT
          # dhcp
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 67 -j ACCEPT
          # dlna
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 8200 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 1900 -j ACCEPT

          #####
          # nat
          # pre-routing
          # voip
          # http://serverfault.com/questions/594835/what-is-the-correct-way-to-open-a-range-of-ports-in-iptables
          # Good voip guide, note the comment to limit stp to smaller port range
          # http://whirlpool.net.au/wiki/iiNetPhone_asterisk

          # 15000: # 35000-44999
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 5060 -i eth0.120 -j DNAT --to 192.168.201.20
          # iptables -t nat -A PREROUTING -p tcp --match multiport --dport 5060 -i eth0.120 -j DNAT --to 192.168.201.20
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 15000:49999 -i eth0.120 -j DNAT --to 192.168.201.20

          # with nat punch-through it's not clear we even need all this
          # or at least tcp on 5060?
          # port forward may even confuse
          iptables -t nat -A PREROUTING -p udp -s 203.55.231.0/24 -i eth0.120 -j DNAT --to 192.168.201.20
          iptables -t nat -A PREROUTING -p tcp -s 203.55.231.0/24 -i eth0.120 -j DNAT --to 192.168.201.20

          # post-routing
          # private subnet nat
          iptables -t nat -A POSTROUTING -s 10.0.0.0/8     -o eth0.120 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 172.16.0.0/12  -o eth0.120 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o eth0.120 -j MASQUERADE

          #####
          # mangle

      notify: reconfigure-iptables

    # multicast subnet routing. for example minidlna udp on 1900
    # Use, ip -s mroute to query status
    - apt: name=smcroute
    - copy:
        dest: /etc/smcroute/startup.sh
        mode: 0755
        content: |
          # deployed by ansible!
          sleep 1
          smcroute -a wlan0    0.0.0.0 239.255.255.250 eth0.201
          smcroute -a eth0.201 0.0.0.0 239.255.255.250 wlan0
      notify: restart-smcroute

    - apt: name=tftp
    - copy:
        dest: /etc/default/tftpd-hpa
        mode: 0644
        content: |
          # deployed by ansible!
          TFTP_USERNAME="tftp"
          TFTP_DIRECTORY="/srv/tftp"
          TFTP_ADDRESS="0.0.0.0:69"
          TFTP_OPTIONS="--secure --port-range 1024:1034"
      notify: restart-tftpd-hpa

      # /srv/tftp cannot just be owned by tftp. instead must have global read permissions
      # chown -R root:root /srv/tftp
      # chmod 755 $( find /srv/tftp -type d )
      # chmod 644 $( find /srv/tftp -type f )

    # xmodem protocol support over serial for switch firmware
    - apt: name=lrzsz



  handlers:
    - name: restart-eth0
      command: sh -c "/sbin/ifdown eth0 && /sbin/ifup eth0"

    - name: restart-wlan0
      command: sh -c "/sbin/ifdown wlan0 && sleep 1 && /sbin/ifup wlan0"

    - name: restart-eth0
      command: sh -c "/sbin/ifdown eth0 && /sbin/ifup eth0"

    - name: restart-eth1
      command: sh -c "/sbin/ifdown eth1 && /sbin/ifup eth1"

    - name: restart-smcroute
      service: name=smcroute state=restarted

    - name: restart-tftpd-hpa
      service: name=tftpd-hpa state=restarted


