
# apt
- copy:
    dest: /etc/apt/sources.list
    content: |
      # deployed by ansible!

      deb http://ftp.au.debian.org/debian/ buster                   main contrib non-free
      deb http://security.debian.org/debian-security buster/updates main contrib non-free
      deb http://ftp.au.debian.org/debian/ buster-updates           main contrib non-free



