
  - git: repo=https://github.com/julian1/dapple dest=dapple version=master

  # For secp256k1 maybe others
  - apt: name=make
  - apt: name=g++

  - shell: creates=git-remotes chdir=dapple {{item}}
    with_items:
      - git remote add nexus https://github.com/NexusDevelopment/dapple
      - git fetch nexus
      - git checkout nexus/master
      - touch git-remotes
      - npm link               # from dapple docs
      # - npm install


