
  # eg. ansible-playbook ./plays/deploy-war.yml -i n.n.n.n, --extra-vars "warpath=~/imos/geoserver-1.0.0-imos.war warname=geoserver.war"

  # the play forces state change, which is different to an idempotent action...
  # think this makes the use cases different.

  - set_fact: tomcat7=/var/lib/tomcat7
  - set_fact: webapps={{tomcat7}}/webapps
  - set_fact: logs={{tomcat7}}/logs

  # - set_fact: conf={{tomcat7}}/conf
  # - set_fact: lib={{tomcat7}}/lib

  - service: name=tomcat7 state=stopped


  # remove old stuff
  - find: path="{{webapps}}" file_type=file
    register: files

  - find: path="{{webapps}}" file_type=directory
    register: directories

  - file: state=absent path={{ item.path }}
    with_items: 
      - "{{ files.files }}"
      - "{{ directories.files }}"



  # clear catalina
  - shell: "{{item}}"
    with_items:
      - echo > {{logs}}/catalina.out


  # install
  - copy: src={{warpath}} dest={{webapps}}/{{warname}}

  # check md5sum
  - command: md5sum {{webapps}}/{{warname}}
    register: result
    ignore_errors: True

  - debug: msg="{{result.stdout}}" #"


  - service: name=tomcat7 state=started

