
  # needs the following DNS records - MX, A, SPF, PTR (via host)

  - apt: name=postfix

  - apt: name=postfix-policyd-spf-python

  - copy:
      dest: /etc/postfix/main.cf
      content: |
        # deployed by ansible!


        # JA...
        # myhostname = debian-512mb-sgp1-01.localdomain
        # myhostname = debian-512mb-sgp1-01.localdomain
        myhostname = mail.julian1.io
        alias_maps = hash:/etc/aliases
        alias_database = hash:/etc/aliases
        myorigin = /etc/mailname
        # JA
        mydestination = $myhostname, localhost
        relayhost =
        # mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
        mynetworks = 127.0.0.0/8
        mailbox_size_limit = 0
        recipient_delimiter = +
        inet_interfaces = all
        inet_protocols = all


        # Debian specific:  Specifying a file name will cause the first
        # line of that file to be used as the name.  The Debian default
        # is /etc/mailname.
        #myorigin = /etc/mailname

        smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
        biff = no

        # appending .domain is the MUA's job.
        append_dot_mydomain = no

        # Uncomment the next line to generate "delayed mail" warnings
        #delay_warning_time = 4h

        readme_directory = no

        # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
        # fresh installs.
        compatibility_level = 2

        # JA https://www.reddit.com/r/selfhosted/comments/4pi5r1/how_to_send_email_encrypted/
        # http://www.postfix.org/TLS_README.html
        smtp_tls_security_level = may

        # TLS parameters
        smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
        smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        smtpd_use_tls=yes
        smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
        smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

        # See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
        # information on enabling SSL in the smtp client.

        # JA
        # smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
        smtpd_recipient_restrictions =
           permit_mynetworks
           permit_sasl_authenticated
           reject_unauth_destination
           check_policy_service unix:private/policy-spf


        # JA SPF
        policy-spf_time_limit = 3600s

    # think this restarts it
    notify: reconfigure-postfix
    tags: whoot



  # SPF see
  #   https://help.ubuntu.com/community/Postfix/SPF
  #   https://www.linode.com/docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8
  # $ default configuration, grep -v ^# /etc/postfix/master.cf
  - copy:
      dest: /etc/postfix/master.cf
      content: |
        # deployed by ansible!
        smtp      inet  n       -       y       -       -       smtpd
        pickup    unix  n       -       y       60      1       pickup
        cleanup   unix  n       -       y       -       0       cleanup
        qmgr      unix  n       -       n       300     1       qmgr
        tlsmgr    unix  -       -       y       1000?   1       tlsmgr
        rewrite   unix  -       -       y       -       -       trivial-rewrite
        bounce    unix  -       -       y       -       0       bounce
        defer     unix  -       -       y       -       0       bounce
        trace     unix  -       -       y       -       0       bounce
        verify    unix  -       -       y       -       1       verify
        flush     unix  n       -       y       1000?   0       flush
        proxymap  unix  -       -       n       -       -       proxymap
        proxywrite unix -       -       n       -       1       proxymap
        smtp      unix  -       -       y       -       -       smtp
        relay     unix  -       -       y       -       -       smtp
        showq     unix  n       -       y       -       -       showq
        error     unix  -       -       y       -       -       error
        retry     unix  -       -       y       -       -       error
        discard   unix  -       -       y       -       -       discard
        local     unix  -       n       n       -       -       local
        virtual   unix  -       n       n       -       -       virtual
        lmtp      unix  -       -       y       -       -       lmtp
        anvil     unix  -       -       y       -       1       anvil
        scache    unix  -       -       y       -       1       scache
        maildrop  unix  -       n       n       -       -       pipe
          flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
        uucp      unix  -       n       n       -       -       pipe
          flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
        ifmail    unix  -       n       n       -       -       pipe
          flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
        bsmtp     unix  -       n       n       -       -       pipe
          flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
        scalemail-backend unix  -       n       n       -       2       pipe
          flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
        mailman   unix  -       n       n       -       -       pipe
          flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
          ${nexthop} ${user}

        # JA SPF
        policy-spf  unix  -       n       n       -       -       spawn
          user=nobody argv=/usr/bin/policyd-spf

    # think this restarts it
    notify: reconfigure-postfix
    tags: whoot


