
  # TODO move to node specific role

  # needs the following DNS records - MX, A, SPF, PTR (via host), TXT (same as SPF)
  # julian1.io
  #   MX 10 mail.julian1.io - - 60
  #   SPF "v=spf1 mx -all" - - 60
  #   TXT "v=spf1 mx -all" - - 60
  # 
  # mail._domainkey.julian1.io 
  #   TXT  "v=DKIM1; h=sha256; k=rsa; " "p=... " "..." 
  # 
  # mail
  #   A n.n.n.n  - - 60
  # 
  # (host provider)
  #   PTR


  # TODO maybe move logging out of /var/log/syslog.

  - apt: name=postfix

  - apt: name=postfix-policyd-spf-python

  - copy:
      dest: /etc/postfix/main.cf
      content: |
        # deployed by ansible!

        # JA
        # set myhostname, in case the machine name isn't set to a fully-qualified domain name
        myhostname = mail.julian1.io

        # JA
        # not sure if used, or convenience var
        mydomain = julian1.io

        # The myorigin parameter specifies the domain that appears in mail that is posted
        # on this machine. The default is to use the local machine name, $myhostname,
        # which defaults to the name of the machine. Unless you are running a really
        # small site, you probably want to change that into $mydomain,
        myorigin = julian1.io

        # JA not used
        alias_maps = hash:/etc/aliases
        alias_database = hash:/etc/aliases

        # JA
        # The mydestination parameter specifies what domains this machine will deliver locally,
        mydestination = $myhostname, $mydomain, localhost

        relayhost =
        # mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
        mynetworks = 127.0.0.0/8
        mailbox_size_limit = 0
        recipient_delimiter = +
        inet_interfaces = all
        inet_protocols = all


        # Debian specific:  Specifying a file name will cause the first
        # line of that file to be used as the name.  The Debian default
        # is /etc/mailname.
        #myorigin = /etc/mailname

        smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
        biff = no

        # appending .domain is the MUA's job.
        append_dot_mydomain = no

        # Uncomment the next line to generate "delayed mail" warnings
        #delay_warning_time = 4h

        readme_directory = no

        # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
        # fresh installs.
        compatibility_level = 2

        # JA https://www.reddit.com/r/selfhosted/comments/4pi5r1/how_to_send_email_encrypted/
        # http://www.postfix.org/TLS_README.html
        smtp_tls_security_level = may

        # TLS parameters
        smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
        smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        smtpd_use_tls=yes
        smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
        smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

        # See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
        # information on enabling SSL in the smtp client.

        # JA
        # smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
        smtpd_recipient_restrictions =
           permit_mynetworks
           permit_sasl_authenticated
           reject_unauth_destination
           check_policy_service unix:private/policy-spf


        # JA SPF
        policy-spf_time_limit = 3600s

        # JA DKIM
        # https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy
        milter_protocol = 2
        milter_default_action = accept

        smtpd_milters = inet:localhost:12301
        non_smtpd_milters = inet:localhost:12301



    # restarts it
    notify: reconfigure-postfix
    tags: whoot


  ##############################################

  # SPF see
  #   https://help.ubuntu.com/community/Postfix/SPF
  #   https://www.linode.com/docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8
  # $ default configuration, grep -v ^# /etc/postfix/master.cf
  - copy:
      dest: /etc/postfix/master.cf
      content: |
        # deployed by ansible!
        smtp      inet  n       -       y       -       -       smtpd
        pickup    unix  n       -       y       60      1       pickup
        cleanup   unix  n       -       y       -       0       cleanup
        qmgr      unix  n       -       n       300     1       qmgr
        tlsmgr    unix  -       -       y       1000?   1       tlsmgr
        rewrite   unix  -       -       y       -       -       trivial-rewrite
        bounce    unix  -       -       y       -       0       bounce
        defer     unix  -       -       y       -       0       bounce
        trace     unix  -       -       y       -       0       bounce
        verify    unix  -       -       y       -       1       verify
        flush     unix  n       -       y       1000?   0       flush
        proxymap  unix  -       -       n       -       -       proxymap
        proxywrite unix -       -       n       -       1       proxymap
        smtp      unix  -       -       y       -       -       smtp
        relay     unix  -       -       y       -       -       smtp
        showq     unix  n       -       y       -       -       showq
        error     unix  -       -       y       -       -       error
        retry     unix  -       -       y       -       -       error
        discard   unix  -       -       y       -       -       discard
        local     unix  -       n       n       -       -       local
        virtual   unix  -       n       n       -       -       virtual
        lmtp      unix  -       -       y       -       -       lmtp
        anvil     unix  -       -       y       -       1       anvil
        scache    unix  -       -       y       -       1       scache
        maildrop  unix  -       n       n       -       -       pipe
          flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
        uucp      unix  -       n       n       -       -       pipe
          flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
        ifmail    unix  -       n       n       -       -       pipe
          flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
        bsmtp     unix  -       n       n       -       -       pipe
          flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
        scalemail-backend unix  -       n       n       -       2       pipe
          flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
        mailman   unix  -       n       n       -       -       pipe
          flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
          ${nexthop} ${user}

        # JA SPF
        policy-spf  unix  -       n       n       -       -       spawn
          user=nobody argv=/usr/bin/policyd-spf


    # reconfigure and restart handler
    notify: reconfigure-postfix
    tags: whoot



  ##############################################

  # NOte, that we are not generating restart events for all actions, so potentially need manual restart of dkim
  # checking dns record, 
  #  dig google._domainkey.protodave.com TXT
  #  dig mail._domainkey.julian1.io TXT 
  # note that p really is in two parts,

  - apt: name=opendkim
  - apt: name=opendkim-tools   # for signing tool,


  # https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy
  - copy:
      dest: /etc/opendkim.conf
      content: |
        # deployed by ansible!

        AutoRestart             Yes
        AutoRestartRate         10/1h
        UMask                   002
        Syslog                  yes
        SyslogSuccess           Yes
        LogWhy                  Yes

        Canonicalization        relaxed/simple

        ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
        InternalHosts           refile:/etc/opendkim/TrustedHosts
        KeyTable                refile:/etc/opendkim/KeyTable
        SigningTable            refile:/etc/opendkim/SigningTable

        Mode                    sv
        PidFile                 /var/run/opendkim/opendkim.pid
        SignatureAlgorithm      rsa-sha256

        UserID                  opendkim:opendkim

        Socket                  inet:12301@localhost
    # restarts it
    notify: reconfigure-dkim
    tags: whoot


  - copy:
      dest: /etc/default/opendkim
      content: |
        # deployed by ansible!

        #DAEMON_OPTS=""
        RUNDIR=/var/run/opendkim
        # JA
        SOCKET="inet:12301@localhost"
        USER=opendkim
        GROUP=opendkim
        PIDFILE=$RUNDIR/$NAME.pid
        EXTRAAFTER=

    # restarts it
    notify: reconfigure-dkim
    tags: whoot


  - file: path=/etc/opendkim        state=directory owner=root group=opendkim
  - file: path=/etc/opendkim/keys   state=directory owner=root group=opendkim


  - copy:
      dest: /etc/opendkim/TrustedHosts
      content: |
        # deployed by ansible!

        127.0.0.1
        localhost
        192.168.0.1/24

        *.julian1.io

  - copy:
      dest: /etc/opendkim/KeyTable
      content: |
        # deployed by ansible!

        mail._domainkey.julian1.io julian1.io:mail:/etc/opendkim/keys/julian1.io/mail.private

  - copy:
      dest: /etc/opendkim/SigningTable
      content: |
        # deployed by ansible!

        *@julian1.io mail._domainkey.julian1.io


  - file: path=/etc/opendkim/keys/julian1.io   state=directory owner=root group=opendkim


  # generate keys 
  - command: opendkim-genkey -s mail -d julian1.io
    args:
      chdir:  /etc/opendkim/keys/julian1.io
      creates: mail.private

  
  - file: path=/etc/opendkim/keys/julian1.io/mail.private     owner=opendkim group=root
    tags: whooter


