
  # Geth
  # build/bin/geth --help | less
  # build/bin/geth --datadir /home/meteo/data
  # etc

  - debug: msg="building geth"
  - apt: name=make
  - apt: name=gcc
  - apt: name=libgmp-dev

  # geth 1.6.7 needs go version 1.7 or later, which is available in stretch
  # else check golang role
  - apt: name=golang

  # sudo for become_user - to reduce permissions when running build
  - apt: name=sudo
  - apt: name=git

  # g co v1.4.10
  # - git: repo=https://github.com/ethereum/go-ethereum dest={{path}}/go-ethereum version=v1.3.6
  - git: repo=https://github.com/ethereum/go-ethereum dest={{build_dir}}/go-ethereum version=v1.6.7
    become: true
    become_user: "{{user}}"

  - shell: make creates=build/bin/geth chdir={{build_dir}}/go-ethereum
    become: true
    become_user: "{{user}}"

