
OBSOLETE - this is only for passwordless sudo - which we don't generally want.

  - apt: name=sudo

  - lineinfile: >
      dest=/etc/sudoers
      validate='visudo -cf %s'
      state=present
      insertafter=EOF
      "line=%adm ALL=(ALL) NOPASSWD: ALL"


