


  - copy:
      dest: /usr/local/bin/smaller.sh
      mode: 0777
      src: smaller.sh

  - copy:
      dest: /usr/local/bin/backup.sh
      mode: 0777
      src: backup.sh

  - copy:
      dest: /usr/local/bin/restore.sh
      mode: 0777
      src: restore.sh

  - copy:
      dest: /usr/local/bin/brightness.sh
      mode: 0777
      src: brightness.sh

  - copy:
      dest: /usr/local/bin/volume.sh
      mode: 0777
      src: volume.sh

  - copy:
      dest: /usr/local/bin/rsync-phone-pics-a20.sh
      mode: 0777
      src: rsync-phone-pics-a20.sh


