
  - file: path="{{path}}" state=directory owner="{{user}}" group="{{user}}" recurse=yes

  - copy:
      dest: "{{path}}/backup.sh"
      mode: 0755
      src: backup.sh

  - copy:
      dest: "{{path}}/restore.sh"
      mode: 0755
      src: restore.sh

  - copy:
      dest: "{{path}}/brightness.sh"
      mode: 0755
      src: brightness.sh

  - copy:
      dest: "{{path}}/volume.sh"
      mode: 0755
      src: volume.sh

  - copy:
      dest: "{{path}}/smaller.sh"
      mode: 0755
      src: smaller.sh



  # see low-battery-alert role for actual cron configuration and deploy.
  - copy:
      dest: "{{path}}/low-battery-alert.sh"   # FIXME
      mode: 0777
      owner: "{{user}}"
      group: "{{user}}"
      src: low-battery-alert.sh

  # any phone with simplesshd
  - copy:
      dest: "{{path}}/rsync-phone.sh"
      mode: 0755
      owner: "{{user}}"
      group: "{{user}}"
      src: rsync-phone.sh

  - copy:
      dest: "{{path}}/send-to-phone.sh"
      mode: 0755
      owner: "{{user}}"
      group: "{{user}}"
      src: send-to-phone.sh




################

# doesn't work so well
#  - copy:
#      dest: /usr/local/bin/sshfs-phone.sh
#      mode: 0755
#      owner: me
#      group: me
#      src: sshfs-phone.sh



################

#
#  - copy:
#      dest: /usr/local/bin/rsync-phone-pics-a20.sh
#      mode: 0755
#      src: rsync-phone-pics-a20.sh
#
#  - copy:
#      dest: /usr/local/bin/rsync-phone-travel.sh
#      mode: 0755
#      src: rsync-phone-travel.sh
#
#
#  - copy:
#      dest: /usr/local/bin/find-cabal-sandbox.sh
#      mode: 0755
#      src: find-cabal-sandbox.sh
#

