

  - copy:
      dest: /usr/local/bin/backup.sh
      mode: 0755
      src: backup.sh

  - copy:
      dest: /usr/local/bin/restore.sh
      mode: 0755
      src: restore.sh

  - copy:
      dest: /usr/local/bin/brightness.sh
      mode: 0755
      src: brightness.sh

  - copy:
      dest: /usr/local/bin/volume.sh
      mode: 0755
      src: volume.sh

  - copy:
      dest: /usr/local/bin/smaller.sh
      mode: 0755
      src: smaller.sh



  # see low-battery-alert role for actual cron configuration and deploy.
  - copy:
      dest: /usr/local/bin/low-battery-alert.sh
      mode: 0777
      owner: me
      group: me
      src: low-battery-alert.sh

  # a20 phone
  - copy:
      dest: /usr/local/bin/rsync-phone.sh
      mode: 0755
      owner: me
      group: me
      src: rsync-phone.sh

  # a20  not good for full backup due to fuse file locking, but easier than jmtpfs for simple copying/dir exploring
  - copy:
      dest: /usr/local/bin/sshfs-phone.sh
      mode: 0755
      owner: me
      group: me
      src: sshfs-phone.sh




################

# doesn't work so well
#  - copy:
#      dest: /usr/local/bin/sshfs-phone.sh
#      mode: 0755
#      owner: me
#      group: me
#      src: sshfs-phone.sh



################

#
#  - copy:
#      dest: /usr/local/bin/rsync-phone-pics-a20.sh
#      mode: 0755
#      src: rsync-phone-pics-a20.sh
#
#  - copy:
#      dest: /usr/local/bin/rsync-phone-travel.sh
#      mode: 0755
#      src: rsync-phone-travel.sh
#
#
#  - copy:
#      dest: /usr/local/bin/find-cabal-sandbox.sh
#      mode: 0755
#      src: find-cabal-sandbox.sh
#

