
  # TODO maybe parametize
  # NOTE the symbolic-link /var/lib/tomcat7/conf -> /etc/tomcat7


  - apt: name=tomcat7 update_cache=yes

  - file: > 
      path="{{item}}"
      state=directory owner=tomcat7 group=tomcat7 
    tags: whoot
    with_items:
      - "{{tomcat7}}"
      - "{{webapps}}"
      - "{{overrides}}"
      - "{{geonetwork_data}}"
      - "{{config}}"
      - "{{schema_plugins}}"
      - "{{codelist}}"
      - "{{geonetwork}}"
      - "{{thesauri_theme}}"


  # jndi
  - template: src=context.j2 dest={{conf}}/context.xml owner=tomcat7 group=tomcat7
    notify: restart-tomcat7

  # tomcat opts
  # TODO maybe remove config-conf/overrides from here, and instead define in context.xml
  - template: src=tomcat7.j2 dest=/etc/default/tomcat7 owner=tomcat7 group=tomcat7
    notify: restart-tomcat7


  # overrides
  - debug: msg="setting up config-overides"
  - file: path={{overrides}} state=directory owner=tomcat7
  - template: src=config-overrides.j2 dest={{overrides}}/config-overrides.xml owner=tomcat7 group=tomcat7
  - template: src=log4j-overrides.j2  dest={{overrides}}/log4j-overrides.xml  owner=tomcat7 group=tomcat7


  # war
  # TODO make war source configurable

  - debug: msg="getting war"
  - get_url: >
      url=https://jenkins.aodn.org.au/job/geonetwork_prod/lastSuccessfulBuild/artifact/web/target/geonetwork.war
      dest={{webapps}}/geonetwork.war
    notify: restart-tomcat7




  # Unpack war to make iso19139 available
  - debug: msg="unpacking war"
  - apt: name=unzip
  - file: path={{geonetwork}} state=directory
  - unarchive: src={{webapps}}/geonetwork.war dest={{geonetwork}} copy=no
  - file: path={{geonetwork}} owner=tomcat7 group=tomcat7 recurse=yes


  # Schema plugins
  - debug: msg="schema plugins"
  # https://github.com/ansible/ansible/issues/7474
  - shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts creates=/etc/ssh/ssh_known_hosts
  - git: repo=https://github.com/aodn/schema-plugins  dest={{aodn_schema_plugins}} version=master # # master  version=merge-imos-to-2.10.x
    notify: restart-tomcat7
  - file: path={{aodn_schema_plugins}} state=directory owner=tomcat7 group=tomcat7

  # Only link needed schema-plugins
  - file: >
      src={{geonetwork}}/WEB-INF/data/config/schema_plugins/iso19139
      dest={{schema_plugins}}/iso19139
      state=link owner=tomcat7 group=tomcat7


  # for some reason variables (eg. aodn_schema_plugins are not expanded properly
  - file: > 
      src=/var/lib/tomcat7/conf/aodn-schema-plugins/{{item}}
      dest=/var/lib/tomcat7/conf/geonetwork_data/config/schema_plugins/{{item}} 
      state=link owner=tomcat7 group=tomcat7
    # tags: whoot
    with_items:
      - iso19139.mcp
      - iso19139.mcp-2.0
      - iso19139.anzlic
      - iso19135
      - iso19139.mcp-1.4


  # codelists

  #  - debug: msg="codelists"
  #  - git: repo=https://github.com/aodn/codelist dest={{codelist}} version=master force=yes
  #  - file: path={{codelist}} owner=tomcat7 group=tomcat7 recurse=yes
  # http://content.aodn.org.au/Vocabularies/discovery-parameter/aodn_aodn-discovery-parameter-vocabulary.rdf 

  - get_url: url="{{item.url}}" dest="{{item.dest}}"
    tags: whoot
    with_items:
      - { url: "{{vocab_url}}/discovery-parameter/aodn_aodn-discovery-parameter-vocabulary.rdf", 
          dest: "{{thesauri_theme}}/aodn_aodn-discovery-parameter-vocabulary.rdf" } 




