

  # TODO make a role, and control size with a var

  - shell: creates=/swap.ok {{item}}
    with_items:
      - dd if=/dev/zero of=/swap bs=1024 count={{size}}
      - chown root:root /swap
      - chmod 0600 /swap
      - mkswap /swap
      - swapon /swap
      - echo '/swap swap swap defaults 0 0' >> /etc/fstab
      - touch /swap.ok

