
# simpler...
# curl https://sh.rustup.rs -sSf | sh; source $HOME/.cargo/env

#
# parity readme says 1.18.0,
# but v1.6.10 needs rust v1.18.0
# rm -rf .cargo/ rustup-init .rustup/ .multirust

# install rust to top level dir

  # we need to pass the url, so may as well just install locally here...
  - get_url: >
      url='https://sh.rustup.rs'
      dest=/home/{{user}}/rustup-init
      mode=755

  - apt: name=curl
  - apt: name=sudo


    # Note, this will update bash_profile, /home/rust/.cargo/bin/rustc
  - name: rustup
    become: yes
    become_user: "{{user}}"
    command: >
      /home/{{user}}/rustup-init -y
      creates=/home/{{user}}/.rustup/settings.toml


  # install version 1.18.0 and switch to it
  # parity v1.7.6 needed 1.18.0
  - name: install rust
    become: yes
    become_user: "{{user}}"
    shell: >
      # TODO review me!
      export PATH=/home/{{user}}/.cargo/bin:$PATH && rustup install {{version}}  && rustup default {{version}}


 # not idempotent. needs shell, because command handle env vars
#  - name: rustup update
#    become: yes
#    become_user: "{{user}}"
#    shell: >
#      export PATH=/home/{{user}}/.cargo/bin:$PATH && rustup update

