
  # Fairly generic postgres configuration
  # Note, see postgres-apt role for postgres repository install

  - debug: msg="{{ansible_distribution_release}}"

  
  - apt: name=postgresql-{{postgres_version}}-postgis-{{postgis_version}}

  - set_fact: main=/etc/postgresql/{{postgres_version}}/main
  - set_fact: libmain=/var/lib/postgresql/{{postgres_version}}/main

  - copy:
      dest: "{{main}}/postgresql.conf"
      owner: postgres
      content: |
        # deployed by ansible!
        listen_addresses = '*'
        port = 5432
        max_connections = 100
        shared_buffers = '24MB'
        log_line_prefix = '%t %h %u %d %p %e'

        log_statement = all

        # For XA
        max_prepared_transactions = 10          # zero disables the feature

        datestyle = 'iso, mdy'
        default_text_search_config = 'pg_catalog.english'
        ssl = on
        data_directory = '{{libmain}}'
        hba_file = '{{main}}/pg_hba.conf'

        ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
        ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'

    notify: restart-postgres

  - copy:
      dest: "{{main}}/pg_hba.conf"
      owner: postgres
      content: |
        # deployed by ansible!
        hostssl  all  postgres  0.0.0.0/0  reject
        local    all  postgres  peer
        hostssl  all  all       0.0.0.0/0  md5

    notify: restart-postgres

  - file: path=/ansible state=directory


