

  #####
  # alsa
  - apt: name=alsa-oss
  - apt: name=alsa-utils
  - apt: name=alsa-tools


  # command: bash -c "/usr/sbin/alsactl"
  # not sure if this should be with store or init
  # think when run as shell it runs 'init'
  # doc says reboot is needed, https://wiki.debian.org/ALSA
  - command: /usr/sbin/alsactl
    args:
      # feb 2020. no longer created
      creates: /var/lib/alsa/asound.state

    # feb 2020. we did need to reboot. albeit did it manually.
    # then worked out of the box.
    # test using "# speaker-test"
    notify: reboot


