#### xmonad dirs are created as root - when we provision as root. which is required for apt.

- hosts: 
    - localhost

  vars:
  pre_tasks:

    # root user (no ssh)
    - user: >
        name=root
        shell=/bin/bash

    # note staff group has same security implications as root, since can put binaries in /usr/local/bin and usurp root privileges
    # so must be trusted

    # non-priv user (no ssh)
    - user: >
        name=meteo
        shell=/bin/bash
        groups=staff,sudo,tty,cdrom,floppy,audio,dip,video,plugdev,netdev,bluetooth

    - file: >
        path=/home/meteo
        mode=0700
        owner=meteo group=meteo
        state=directory


  roles:
    - name: admin/apt-stretch
      mirror: http://ftp.au.debian.org/debian/

    - admin/devenv-lite   # vim/screen eg. required for anything
    - admin/timezone
    - admin/locale
    # call role twice for different users?

    # https://serverfault.com/questions/758376/local-ansible-playbook-run-playbook-with-vars-for-role
    - name: personal/dotfiles
      tags: dotfiles
      path: /home/meteo
      user: meteo

    - name: personal/pathogen
      tags: pathogen
      pathogen_path: /home/meteo
      pathogen_user: meteo

    - name: personal/xmonad
      tags: xmonad
      xmonad_user: meteo

    # need the user created before we do this...
    - name: personal/scripts
      tags: scripts

    # TODO - should go ini second level stuff...
    - name: admin/printer
      tags: printer
      pname: Brother
      url: socket://brother.localnet:9100
      ppd: BRHL16_2_GPL.ppd

    # very specific configuration
    - name: nodes/dell5520
 
  tasks:


