
  #   zfs is now maintained in debian repos, and doesn't need to be compiled.

  - apt: name=spl-dkms
  - apt: name=zfs-dkms

  #
  - copy:
      dest: /etc/modprobe.d/zfs.conf
      content: |
        # deployed by ansible!
        # see, http://serverfault.com/questions/581669/why-isnt-the-arc-max-setting-honoured-on-zfs-on-linux
        options zfs zfs_arc_max=34359738368
    notify: reboot



  - copy:
      dest: /root/mount.sh
      mode: 0755
      content: |
        #!/bin/bash -x
        # deployed by ansible!

        cryptsetup luksOpen /dev/sda2 myfs || exit
        cryptsetup status myfs || exit
        zpool import storage

  - copy:
      dest: /root/unmount.sh
      mode: 0755
      content: |
        #!/bin/bash -x
        # deployed by ansible!

        zpool export storage
        cryptsetup luksClose myfs

#
#  # reinstall simpler
#  - copy:
#      dest: /root/reinstall-zfs-simple.sh
#      mode: 0755
#      content: |
#        #!/bin/bash -x
#        # deployed by ansible!
#
#        apt-get install linux-headers-$( uname -r )
#        apt-get install --reinstall zfs-dkms
#
#
#  # reinstall
#  - copy:
#      dest: /root/reinstall-zfs.sh
#      mode: 0755
#      content: |
#        #!/bin/bash -x
#        # deployed by ansible!
#
#        apt-get -y purge spl
#        apt-get -y purge spl-*
#        apt-get -y purge kmod-spl*
#        apt-get -y purge spl-dkms
#        apt-get -y purge kmod-zfs*
#        apt-get -y purge zfs*
#        apt-get -y purge libzfs*
#
#        # need correct kernel header version k
#        apt-get -y  install linux-headers-$( uname -r )
#
#        apt-get -y install zfs-dkms
#
#        /sbin/modprobe zfs
#
#




    # TODO get rid of the touch stuff...

    #
    #    - apt: name=dh-autoreconf
    #    - apt: name=alien
    #
    #    - git: repo=https://github.com/zfsonlinux/spl.git dest=/root/spl version=spl-0.6.5-release
    #    - command: ./autogen.sh chdir=/root/spl creates=configure
    #    - command: ./configure chdir=/root/spl creates=Makefile
    #    - shell: make deb-utils deb-kmod chdir=/root/spl creates=kmod-spl-4.3.0-1-amd64_0.6.5.4-2_amd64.deb
    #    - shell: dpkg -i *.deb && touch ansible-installed chdir=/root/spl creates=ansible-installed
    #
    #
    #    - apt: name=uuid-dev
    #    - git: repo=https://github.com/zfsonlinux/zfs.git dest=/root/zfs version=zfs-0.6.5-release
    #    - command: ./autogen.sh chdir=/root/zfs creates=configure
    #    - command: ./configure chdir=/root/zfs creates=Makefile
    #    - shell: make deb-utils deb-kmod chdir=/root/zfs creates=zfs_0.6.5.4-1_amd64.deb
    #    - shell: dpkg -i *.deb && touch ansible-installed chdir=/root/zfs creates=ansible-installed
    #
    #    - modprobe: name=zfs state=present



