
  - name: reconfigure-iptables
    command: "{{item}}"
    with_items:
      - sh -c 'm4 /etc/iptables-rules.m4 > /etc/iptables-rules'
      - sh /etc/iptables-rules
      - dpkg-reconfigure --frontend noninteractive iptables-persistent


