
- hosts: julian-test-instance
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
  vars_files:
    - "{{lookup('env','PWD')}}/credentials.yml"
  roles:
    - jessie
    - update
    - timezone
    - locale
    - meteo

