
- hosts: 
    - portal.localnet
  vars_files:
    - "{{inventory_dir | dirname}}/credentials.yml"
  vars:
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}", home_dir: /home/meteo }
      - { name: root,   group: ,    pubkey: "{{meteo_pubkey}}", home_dir: /root }

    - warpath: "/home/meteo/imos/aodn-portal/target/aodn-portal-4.28.1-production.war" 
    - warname: "portal.war"

  roles:
    - jessie
    - apt-update
    - sshd
    - timezone
    - locale
    - common
    - users
    - dotfiles
    - http-port-forward
    # keep configuration seperate from deployment
#    - portal
#    - { role: deploy-war, tags: [ 'whoot' ] }


  tasks:
    - include: ../roles/devel/tasks/tomcat-bash-aliases.yml
    - include: ../roles/devel/tasks/root-bash-aliases.yml

    # anyone can write the log for easier truncation with echo
    - file: >
        path=/var/lib/tomcat7/logs/catalina.out
        owner=tomcat7 group=tomcat7
        mode=666


    - apt: name=tomcat7 update_cache=yes

    - template: 
        src: ../roles/portal/templates/context.j2 
        dest: /var/lib/tomcat7/conf/context.xml 
        owner: tomcat7 
        group: tomcat7
      notify: restart-tomcat7
      tags: whoot

    - template: 
        src: ../roles/portal/templates/Portal.groovy.j2 
        dest: /var/lib/tomcat7/conf/Portal.groovy 
        owner: tomcat7 
        group: tomcat7
      notify: restart-tomcat7
      tags: whoot

  handlers:
    - name: restart-tomcat7
      service: name=tomcat7 state=restarted



