
#  - name: reconfigure-postfix
#    command: "{{item}}"
#    with_items:
#      # - sh /etc/iptables-rules
#      - dpkg-reconfigure --frontend noninteractive postfix
#

  - name: reconfigure-postfix
    service: name=postfix state=restarted
 
