
#  - name: reconfigure-postfix
#    command: "{{item}}"
#    with_items:
#      # - sh /etc/iptables-rules
#      - dpkg-reconfigure --frontend noninteractive postfix
#

  # change name to restart

  - name: reconfigure-postfix
    service: name=postfix state=restarted

 
  - name: reconfigure-dkim
    service: name=opendkim state=restarted



  - name: reconfigure-dmarc
    service: name=opendmarc state=restarted


