
# TODO all the building should be done as unprivileged user

- hosts: ethereum
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - users:
      - { name: root,     group: ,    pubkey: "{{meteo_pubkey}}" }
      - { name: meteo,    group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - "{{inventory_dir | dirname}}/credentials.yml"
  roles:
    - jessie
    - update
    - timezone
    - locale
    - common
    - dotfiles

  tasks:
    # we want to build all this stuff under an unprivileged account

    # support linking binaries in built in root
    - file: path=/root state=directory mode=0755
#    - include: ../roles/ethereum/tasks/cpp-ethereum.yml
    - include: ../roles/ethereum/tasks/go-ethereum.yml
#    - include: ../roles/devel/tasks/node.yml
#    - include: ../roles/ethereum/tasks/dapple.yml
#    - include: ../roles/ethereum/tasks/vim-solidity.yml
#    - include: ../roles/ethereum/tasks/examples.yml

