# minimal useful stuff for a server
# eg. ansible-playbook plays/server.yml -i parity, -u admin -s

- hosts: all
  roles:
    - admin/apt/update
    - admin/sshd
    - admin/timezone
    - admin/locale
    # - admin/common

