
  # TODO would be good to make the handler notification more robust, so that if a prior event  caused
  # the run to fail, iptables will be correctly reconfigured in a subsequent run

  - apt: name=iptables-persistent
  - copy:
      dest: /etc/iptables-rules
      content: |
        # deployed by ansible!
        iptables -t nat --flush
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080

    notify: reconfigure-iptables

  #### there is no handler....


