
# https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce-1
# copied from postgres


  # TODO review better way?
  - file: path=/ansible state=directory

  - apt: name=wget
  - apt: name=ca-certificates
  - apt: name=apt-transport-https

  
  - copy:
      dest: /etc/apt/sources.list.d/docker.list
      content: |
        # deployed by ansible!
        # note it's 'stable' not 'main'
        deb https://download.docker.com/linux/debian stretch stable


  - shell: creates=/ansible/docker-apt-done.txt chdir=/root {{item}}
    with_items:
      # $ curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      - wget --quiet -O -  https://download.docker.com/linux/debian/gpg | apt-key add -
      - touch /ansible/docker-apt-done.txt

  - apt: state=latest update_cache=yes upgrade=safe

  #
  # install and configure docker in a separate role
  # apt-get install docker-ce
  # docker run hello-world
  #


  # next add user to docker group
  # and, move docker images to where we have storage, 

# systemctl stop docker
# vim /lib/systemd/system/docker.service 

# lineinfile need, 
# ExecStart=/usr/bin/dockerd -H fd:// -g /home/docker

# systemctl daemon-reload
# systemctl start docker
# ps axf | grep docker


