
- hosts: nuc
  tasks:
    - copy:
        dest: /storage/.config/udev.rules.d/81-bluetooth-hci.rules
        content: |
          # deployed by ansible!
          # Intel Bluetooth should be disabled
          # https://projectgus.com/2014/09/blacklisting-a-single-usb-device-from-linux/
          SUBSYSTEM=="usb", ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0a2a", ATTR{authorized}="0"


