
#  "Every .conf file can be overridden with a file named .local. The .conf file
#  is read first, then .local, with later settings overriding earlier ones.
#  Thus, a .local file doesn't have to include everything in the corresponding
#  .conf file, only those settings that you wish to override. Modifications
#  should take place in the .local and not in the .conf.

  # cleans up logging of /var/log/auth.log least ...

  - apt: name=fail2ban
    tags: fail2ban


  # once only
  - command: cp jail.conf jail.local
    args:
      chdir:  /etc/fail2ban/
      creates: jail.local
    tags: fail2ban

  # change to work on [default] ?

  - blockinfile:
      dest: /etc/fail2ban/jail.local
      insertafter: '^\[sshd\].*'
      marker: "# {mark} ansible content"
      content: |
        bantime = 86400
        findtime = 86400
        maxretry = 3
    notify: restart-fail2ban
    tags: fail2ban



