

  - debug: msg="dotfiles path {{user}}"  # " 

  - apt: name=xorg

  # - apt: name=xserver-xorg-input-synaptics   # for synclient  - not for stretch and above
  # mouse sstuff
  # - apt: name=xserver-xorg-input-synaptics state=absent


  # TODO add meteo to group tty

  - apt: name=xmonad
  - apt: name=xmobar
  - apt: name=dmenu
  - apt: name=xtrlock


  # we could potentially put xinitrc here, except it differs between deployments, eg. keybindings


  - copy: src=xinitrc             dest=/home/{{user}}/.xinitrc   owner={{user}} group={{user}}


  - copy: src=40-libinput.conf    dest=/usr/share/X11/xorg.conf.d/40-libinput.conf   

  - copy: src=xmobarrc            dest=/home/{{user}}/.xmobarrc   owner={{user}} group={{user}}

  # this may be default created when installing xmonad
  - file: path="/home/{{user}}/.xmonad" state=directory mode=0755   owner={{user}} group={{user}}

  - copy: src=xmonad.hs           dest=/home/{{user}}/.xmonad/xmonad.hs  owner={{user}} group={{user}}



