
  # TODO consolidate 

  # local changes not in dotfiles for .bashrc
  # TODO put in ./roles/tomcat7 ?
  - copy:
      # shouldn't be hardcoded - because might overwrite another bash_aliases
      # or else we can move somewhere else.
      dest: /home/meteo/.bash_aliases1
      content: |
        # deployed by ansible!
        export L=/var/lib/tomcat7/logs/catalina.out

        alias tl='less $L'
        alias tc='echo > $L'
        alias tp='sudo systemctl stop tomcat7'
        alias ts='sudo sh -c "echo > $L && systemctl start tomcat7"'    # '
        alias tr='sudo sh -c "echo > $L && systemctl restart tomcat7"'  # ' 


