
# TODO use the LOCAL_PORT_FORWARD macro in http-server

# this doesn't compose very well, because it assumes control of iptables chains,
# note, may need, sysctl -w net.ipv4.conf.all.route_localnet=1

  - apt: name=iptables-persistent

  - copy:
      dest: /etc/iptables-rules
      content: |
        # deployed by ansible!
        # note, how internal net redirect is done on the output table, not input table, where it is not supported

        iptables -t nat --flush

        # TODO use the LOCAL_PORT_FORWARD macro in http-server

        # iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
        iptables -t nat -A PREROUTING -p tcp --dport {{from_port}}                 -j REDIRECT --to-ports {{to_port}}
        iptables -t nat -A OUTPUT     -p tcp --dport {{from_port}} -d 127.0.0.0/16 -j REDIRECT --to-ports {{to_port}}

    notify: reconfigure-iptables

