
  #####
  # wireless
  # non-free firmware load for iwlwifi-7260-17.ucode  - worked!

  - apt: name=firmware-iwlwifi   # needs non-free in sources

  - apt: name=wireless-tools  # iwconfig - useful to check wlan1 state
  - apt: name=iw

  - apt: name=wicd-curses

  #####
  # alsa
  - apt: name=alsa-oss
  - apt: name=alsa-utils
  - apt: name=alsa-tools


  # command: bash -c "/usr/sbin/alsactl"
  # not sure if this should be with store or init
  # think when run as shell it runs 'init'
  # doc says reboot is needed, https://wiki.debian.org/ALSA
  - command: /usr/sbin/alsactl
    args:
      creates: /var/lib/alsa/asound.state
    notify: reboot



  # make thumbdrive device writable for dd, by unpriviledged user
  - copy:
      dest: /lib/udev/rules.d/99-z.rules
      content: |
        # deployed by ansible!
        # allow writing /dev/sdb device

        # to reload,
        # udevadm control --reload-rules && udevadm trigger
        # KERNEL=="sdb", SUBSYSTEM=="block", ATTRS{idVendor}=="058f", ATTRS{idProduct}=="6387", MODE="0666", OWNER="meteo"
        SUBSYSTEM=="block", ATTRS{idVendor}=="058f", ATTRS{idProduct}=="6387", MODE="0666", OWNER="meteo"




  ####
  # Bluetooth
  # also, disable bluetooth with systemd
  # https://askubuntu.com/questions/744640/best-way-to-deactivate-bluetooth-on-system-startup-with-systemd-and-not-upstar
  #
  # systemctl stop bluetooth.service
  # systemctl disable bluetooth.service
  # systemctl status bluetooth.service


  #####
  # X
  - copy:
      dest: /home/meteo/.xinitrc
      content: |
        # deployed by ansible!

        # https://raspberrypi.stackexchange.com/questions/752/how-do-i-prevent-the-screen-from-going-blank
        xset s off         # don't activate screensaver
        xset -dpms         # disable DPMS (Energy Star) features.
        xset s noblank     # don't blank the video device
        # xset -dpms; xset s off

        xrdb -merge <<- EOF
          XTerm*selectToClipboard: true
          XTerm*faceName: DejaVu Sans Mono
          XTerm*faceSize: 11   ! laptop
          XTerm*Background: white
          XTerm*Foreground: black
        EOF

        # keymap
        xmodmap - <<- EOF
          ! numpad insert

          keycode 90 = Insert NoSymbol Insert

          # TODO - no longer used
          ! next and prev
          !  = Prior NoSymbol Prior
          !  = Next NoSymbol Next

          ! page up
          keycode 91 =  Up NoSymbol Up

          ! page down
          keycode 104 = Down NoSymbol Down

          ! numpad 2
          keycode 88 =  Home NoSymbol Home

          ! numpad 3
          keycode 89  = End  NoSymbol End
        EOF

        # brightness
        # xrandr --output eDP1 --brightness .45
        xrandr --output eDP-1 --brightness .35

        # start pulse audio
        pulseaudio --kill
        sleep 0.5
        pulseaudio --start

        # MAY OR MAY NOT BE NEEDED with change to libinput replacing synaptics
        # to turn on trackpad tap to select/button
        synclient TapButton1=1

        # turn bell off
        xset b off

        # start xcmonad
        xmonad
    tags: xinitrc


  #####
  # trackpad tapping
  # https://askubuntu.com/questions/838061/touchpad-tap-stopped-working
  #
  # make sure synaptics is not installed
  - apt: name=xserver-xorg-input-synaptics state=absent

  - copy:
      dest: /usr/share/X11/xorg.conf.d/40-libinput.conf
      content: |
        # deployed by ansible!

        # Match on all types of devices but tablet devices and joysticks
        Section "InputClass"
                Identifier "libinput pointer catchall"
                MatchIsPointer "on"
                MatchDevicePath "/dev/input/event*"
                Driver "libinput"
        EndSection

        Section "InputClass"
                Identifier "libinput keyboard catchall"
                MatchIsKeyboard "on"
                MatchDevicePath "/dev/input/event*"
                Driver "libinput"
        EndSection

        Section "InputClass"
                Identifier "libinput touchpad catchall"
                MatchIsTouchpad "on"
                MatchDevicePath "/dev/input/event*"
                # The important bit
                Option "Tapping" "true"
                Driver "libinput"
        EndSection


