
# its a real mistake to be mixing low level stuff - like udev, fstab, kernel modules with scripts, xconfig and timezones.



  #####
  # wireless
  # non-free firmware load for iwlwifi-7260-17.ucode  - worked!

  - apt: name=firmware-iwlwifi   # needs non-free in sources

  - apt: name=wireless-tools  # iwconfig - useful to check wlan1 state
  - apt: name=iw

  - apt: name=wicd-curses



  # root user (no ssh)
  - user:
      name: root
      shell: bin/bash

  # note staff group has same security implications as root, since can put binaries in /usr/local/bin and usurp root privileges
  # so must be trusted
  - user:
      name: meteo-large

  # non-priv user (no ssh)
  - user: >
      name=meteo
      shell=/bin/bash
      groups=meteo-large,docker,staff,sudo,plugdev,tty,cdrom,floppy,audio,dip,video,netdev,bluetooth


  # set more restrictive permissions
  - file: > 
      path=/home/meteo
      mode=0700
      owner=meteo 
      group=meteo
      state=directory




  # make thumbdrive device writable for dd, by unpriviledged user
  # means lower risk - if can avoid su root...
  - copy:
      dest: /lib/udev/rules.d/99-z.rules
      content: |
        # deployed by ansible!
        # allow writing /dev/sdb device

        # to reload,
        # udevadm control --reload-rules && udevadm trigger
        # KERNEL=="sdb", SUBSYSTEM=="block", ATTRS{idVendor}=="058f", ATTRS{idProduct}=="6387", MODE="0666", OWNER="meteo"
        SUBSYSTEM=="block", ATTRS{idVendor}=="058f", ATTRS{idProduct}=="6387", MODE="0666", OWNER="meteo"


  - copy:
      dest: /etc/fstab
      backup: yes
      content: |
        # deployed by ansible!
        # allow writing /dev/sdb device

        # Use 'blkid' to print the universally unique identifier for a
        # device; this may be used with UUID= as a more robust way to name devices
        # that works even if disks are added and removed. See fstab(5).

        # JA all of this is default
        # <file system> <mount point>   <type>  <options>       <dump>  <pass>
        /dev/mapper/nvme0n1p4_crypt /               ext4    errors=remount-ro 0       1
        # /boot was on /dev/nvme0n1p2 during installation
        UUID=695d2c88-d939-4789-853f-3fb9668fb08b /boot           ext4    defaults        0       2
        # /boot/efi was on /dev/nvme0n1p1 during installation
        UUID=2518-1278  /boot/efi       vfat    umask=0077      0       1
        #/dev/mapper/nvme0n1p3_crypt /home           ext4    defaults        0       2

        # JA
        # 2.5" ssd
        UUID=2357e387-a4e0-49cb-9409-278d41c2975d     /home/meteo/mnt/drive ext4  errors=remount-ro 0       2


  ####
  # Bluetooth
  # also, disable bluetooth with systemd
  # https://askubuntu.com/questions/744640/best-way-to-deactivate-bluetooth-on-system-startup-with-systemd-and-not-upstar
  #
  # systemctl stop bluetooth.service
  # systemctl disable bluetooth.service
  # systemctl status bluetooth.service


  # should be moved to xmonad  maybe as a file

  #####
  # X
  - copy:
      dest: /home/meteo/.xinitrc
      content: |
        # deployed by ansible!

        # https://raspberrypi.stackexchange.com/questions/752/how-do-i-prevent-the-screen-from-going-blank
        xset s off         # don't activate screensaver
        xset -dpms         # disable DPMS (Energy Star) features.
        xset s noblank     # don't blank the video device
        # xset -dpms; xset s off

        xset r rate   200   # keyboard repeat rate fixes firefox scrolling
                            # 150 is too short. causes repeat in xterm terminal.


        setxkbmap -option compose:ralt   # accented compose key is right alt

        # setxkbmap -option caps:swapescape   # make caps-lock the escape key, and escape caps-lock. for vim etc.
        setxkbmap -option caps:escape         # to make caps-lock an additional escape

        xrdb -merge <<- EOF
          XTerm*selectToClipboard: true
          XTerm*faceName: DejaVu Sans Mono
          XTerm*faceSize: 11
          XTerm*Background: white
          XTerm*Foreground: black
        EOF

        # keymap
        xmodmap - <<- EOF
          ! numpad insert

          keycode 90 = Insert NoSymbol Insert

          # TODO - no longer used
          ! next and prev
          !  = Prior NoSymbol Prior
          !  = Next NoSymbol Next

          ! page up
          keycode 91 =  Up NoSymbol Up

          ! page down
          keycode 104 = Down NoSymbol Down

          ! numpad 2
          keycode 88 =  Home NoSymbol Home

          ! numpad 3
          keycode 89  = End  NoSymbol End
        EOF

        # brightness
        # xrandr --output eDP1 --brightness .45
        xrandr --output eDP-1 --brightness .35

        # start pulse audio
        pulseaudio --kill
        sleep 0.5
        pulseaudio --start

        # MAY OR MAY NOT BE NEEDED with change to libinput replacing synaptics
        # to turn on trackpad tap to select/button
        synclient TapButton1=1

        # turn bell off
        xset b off

        # start xmonad
        xmonad
    tags: xinitrc


  #####
  # trackpad tapping
  # https://askubuntu.com/questions/838061/touchpad-tap-stopped-working
  #
  # make sure synaptics is not installed
  - apt: name=xserver-xorg-input-synaptics state=absent

  - copy:
      dest: /usr/share/X11/xorg.conf.d/40-libinput.conf
      content: |
        # deployed by ansible!

        # Match on all types of devices but tablet devices and joysticks
        Section "InputClass"
                Identifier "libinput pointer catchall"
                MatchIsPointer "on"
                MatchDevicePath "/dev/input/event*"
                Driver "libinput"
        EndSection

        Section "InputClass"
                Identifier "libinput keyboard catchall"
                MatchIsKeyboard "on"
                MatchDevicePath "/dev/input/event*"
                Driver "libinput"
        EndSection

        Section "InputClass"
                Identifier "libinput touchpad catchall"
                MatchIsTouchpad "on"
                MatchDevicePath "/dev/input/event*"
                # The important bit
                Option "Tapping" "true"
                Driver "libinput"
        EndSection


