
#  - name: reconfigure-postfix
#    command: "{{item}}"
#    with_items:
#      # - sh /etc/iptables-rules
#      - dpkg-reconfigure --frontend noninteractive postfix
#

  # change name to restart

  - name: reconfigure-postfix
    service: name=postfix enabled=yes state=restarted

 
  - name: reconfigure-dkim
    service: name=opendkim enabled=yes state=restarted


  - name: reconfigure-dmarc
    service: name=opendmarc enabled=yes state=restarted


  - name: reconfigure-dovecot
    service: name=dovecot enabled=yes state=restarted

  - name: reconfigure-aliases
    command: "{{item}}"
    with_items:
       - newaliases

