
  # xmonad stuff

  # TODO should not be users. Should be xmonad_users

  - copy: src=xmobarrc        dest={{item.home_dir}}/.xmobarrc
    with_items: users
    when: item.home_dir

  - file: path="{{item.home_dir}}/.xmonad" state=directory mode=0755
    with_items: users
    when: item.home_dir

  - copy: src=xmonad.hs       dest={{item.home_dir}}/.xmonad/xmonad.hs
    with_items: users
    when: item.home_dir

