
  # needed for root bash_aliases
  - copy:
      dest: /root/.bashrc
      content: |
        # deployed by ansible!
        if [ -f ~/.bash_aliases ]; then
            . ~/.bash_aliases
        fi


