

# not sure, if shouldn't be a sh scripted install in a separate github repo, since it's more code

- hosts: all
  roles:
    - name: personal/dotfiles
      path: /home/me
      user: me
      tags: dotfiles

