
# this adjusts group membership so cannot be used generically if a different groups are needed 
# it doesn't change permissions on /home/dir

- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  tasks:

    - user: >
        name=meteo
        password={{meteo_password}}
        groups=sudo




