
# install generic minimal user and environment for server

# eg. ansible-playbook plays/meteo.yml -i parity, -u admin -s

# use meteo-sudo.yml to add sudo and passwd. cannot be made generic, since group membership may be different

- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  pre_tasks:
    - user: name=meteo shell=/bin/bash
    - authorized_key: user=meteo key="{{meteo_pubkey}}"
    - file: path=/home/meteo mode=0700 state=directory

  roles:
    - name: admin/sshd
    - name: admin/timezone
    - name: admin/locale
    - name: admin/devenv-lite

    # note, must manually edit /root/.bashrc to include . .bash_aliases
    # and .vimrc to disable pathogen
    - name: personal/dotfiles
      tags: root_dotfiles
      dotfile_path: /root
      dotfile_user: root


    - name: personal/dotfiles
      tags: dotfiles
      dotfile_path: /home/meteo
      dotfile_user: meteo


    - name: personal/pathogen
      tags: pathogen
      vim_path: /home/meteo
      vim_user: meteo

