

- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  roles:

    # - name: user  name=me shell=/bin/bash

    #- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    #- name: Add user
    #  user:
    #    name: me
    #    shell: /bin/bash

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
#  user:
#    name: johnd
#    comment: John Doe
#    uid: 1040
#    group: admin

#        comment: John Doe
#        uid: 1040
#        group: admin

    # this role should be removed, factored out
    - name: admin/user
      username: me
      path: /home/me
      mode: 0700

    - name: personal/dotfiles
      path: /home/me
      user: me
      tags: dotfiles

    - name: personal/pathogen
      path: /home/me
      user: me
      tags: pathogen

