
# expect to already have /root. 

- hosts: all
  vars_files:
    - ../../credentials.yml
  vars:
  roles:

    - name: personal/dotfiles
      path: /root
      user: root
      tags: root_dotfiles


