
  # TODO would be good to make the handler notification more robust, so that if a prior event  caused
  # the run to fail, iptables will be correctly reconfigured in a subsequent run

  # TODO templatize the port.
  # note, may need, sysctl -w net.ipv4.conf.all.route_localnet=1

  - apt: name=iptables-persistent
  - copy:
      dest: /etc/iptables-rules
      content: |
        # deployed by ansible!
        # note, how internal net redirect is done on the output table, not input table, where it is not supported

        iptables -t nat --flush
        iptables -t nat -A PREROUTING -p tcp --dport 80                 -j REDIRECT --to-ports {{port}}
        iptables -t nat -A OUTPUT     -p tcp --dport 80 -d 127.0.0.0/16 -j REDIRECT --to-ports {{port}}

    notify: reconfigure-iptables

